### ISSUE TITLE
Review and resolve "pending" specs in vets-api

### ISSUE THREAD

**Issue by johnpaulashenfelter** [department-of-veterans-affairs/va.gov-team#10585]
There are a handful of pending specs in the vets-api test suite that have been pending for quite some time. They should either be removed, fixed, or replaced.

The current list of pending specs:

```
Pending: (Failures listed here are expected and do not affect your suite's status)

1) VBADocuments::UploadProcessor#perform sets error status for unexpected attachment part names
    # Temporarily skipped with xit
    # ./modules/vba_documents/spec/jobs/upload_processor_spec.rb:277

2) VBADocuments::UploadProcessor#perform sets error status for non-PDF attachment parts
    # Temporarily skipped with xit
    # ./modules/vba_documents/spec/jobs/upload_processor_spec.rb:274

3) V0::SessionsController when logged in POST saml_callback changing multifactor has a cookie, which includes the testing values
    # Temporarily skipped with xit
    # ./spec/controllers/v0/sessions_controller_spec.rb:423

4) Community Care Providers #show returns RecordNotFound if ppms has no record
    # This needs an updated VCR tape with a request for a provider by id that isnt found

    Failure/Error: expect(bod['errors'][0]['title']).to eq('Record not found')
      Expected "Internal server error" to eq "Record not found"
    # /usr/local/bundle/gems/super_diff-0.4.2/lib/super_diff/rspec/monkey_patches.rb:40:in `handle_failure'
    # ./spec/request/v0/facilities/ccp_request_spec.rb:489:in `block (3 levels) in <top (required)>'
    # ./spec/request/v0/facilities/ccp_request_spec.rb:13:in `block (2 levels) in <top (required)>'

5) VAOS::V1::FHIRService#search when VAMF returns a 500 raises a backend exception with key VAOS_502
    # Temporarily skipped with xit
    # ./modules/vaos/spec/services/v1/fhir_service_spec.rb:70

6) VAOS::V1::FHIRService#search with valid args returns the JSON response body from the VAMF response
    # Temporarily skipped with xit
    # ./modules/vaos/spec/services/v1/fhir_service_spec.rb:88

7) Provider add some examples to (or delete) /srv/vets-api/src/spec/models/provider_spec.rb
    # Not yet implemented
    # ./spec/models/provider_spec.rb:6

8) V1::SessionsController when logged in POST saml_callback changing multifactor has a cookie, which includes the testing values
    # Temporarily skipped with xit
    # ./spec/controllers/v1/sessions_controller_spec.rb:559

9) SAML::User SSOe DSLogon non premium user has various important attributes
    # Temporarily skipped with xit
    # ./spec/lib/saml/ssoe_user_spec.rb:620

10) BB::GenerateReportRequestForm with invalid dates returns valid false with errors
    # Temporarily skipped with xit
    # ./spec/lib/bb/generate_report_request_form_spec.rb:57
```

**Comment by johnpaulashenfelter** [comment]
I believe we need to determine the owner of each of these (eg #7 is Lance Sanchez, 5 and 6 are VAOS, etc) and allocate them. If there's no owner, that's on us.
