### ISSUE TITLE
[Bug] Fix exceptions when generating some nodes

### ISSUE THREAD

**Issue by drorva** [department-of-veterans-affairs/va.gov-team#10961]
# Overview

When bulk generating the nodes based on the CMS export, we are getting exceptions.

# Reproduce
* Setup the instruction to set up your env as described in the [README](https://github.com/department-of-veterans-affairs/vets-website/blob/field-transformer-experiment-cv/script/cms/README.md) 
* run the setup.sh script
  * Specifically node tr.js

# Sample output
```
 Error: ENOENT: no such file or directory, open '/home/dror/tmp/vets-website/.cache/localhost/cms-export-content/undefined.undefined.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at readEntity (/home/dror/tmp/vets-website/src/site/stages/build/process-cms-exports/helpers.js:111:10)
    at fieldData.map.fd (/home/dror/tmp/vets-website/src/site/stages/build/process-cms-exports/transform-fields/index.js:68:20)
    at Array.map (<anonymous>)
    at expandEntityReference (/home/dror/tmp/vets-website/src/site/stages/build/process-cms-exports/transform-fields/index.js:67:20)
    at fieldSchemas.reduce (/home/dror/tmp/vets-website/src/site/stages/build/process-cms-exports/transform-fields/index.js:116:11)
    at Array.reduce (<anonymous>)
    at transformFields (/home/dror/tmp/vets-website/src/site/stages/build/process-cms-exports/transform-fields/index.js:97:23)
    at nodeFiles.map.file (/home/dror/tmp/vets-website/script/cms/transform.js:125:20)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/dror/tmp/vets-website/.cache/localhost/cms-export-content/undefined.undefined.json' }
```
Notice the "undefined.undefined.json"

**Comment by cvalarida** [comment]
Is this still accurate?

**Comment by drorva** [comment]
Now I'm getting:
```
Error encountered while expanding entity references for node.8822bbdd-f5f8-4700-8abb-5566431bd705Error: ENOENT: no such file or directory, open '/home/dror/vsp/vets-website/.cache/localhost/cms-export-content/node.94118509-c27f-466e-9158-724d2aa20733.json'

``

**Comment by drorva** [comment]
The last one is fixed by using prod:
```
NODE_ENV=production yarn build:content --use-cms-export --pull-drupal --buildtype vagovprod
