### ISSUE TITLE
Errors in the build in health-care-region.js

### ISSUE THREAD

**Issue by drorva** [department-of-veterans-affairs/va.gov-team#11627]
During the build we get the following errors. Not clear if the node/data is "dirty" but either way, we should check in the code and avoid getting these exceptions.

```
TypeError: page.fieldLeadership is not iterable
    at createHealthCareRegionListPages (/home/dror/vsp/vets-website/src/site/stages/build/drupal/health-care-region.js:224:24)
    at pipeDrupalPagesIntoMetalsmith (/home/dror/vsp/vets-website/src/site/stages/build/drupal/metalsmith-drupal.js:127:9)
    at Ware.<anonymous> (/home/dror/vsp/vets-website/src/site/stages/build/drupal/metalsmith-drupal.js:270:7)
TypeError: Cannot read property 'entities' of undefined
    at createPastEventListPages (/home/dror/vsp/vets-website/src/site/stages/build/drupal/health-care-region.js:39:13)
    at pipeDrupalPagesIntoMetalsmith (/home/dror/vsp/vets-website/src/site/stages/build/drupal/metalsmith-drupal.js:130:9)
    at Ware.<anonymous> (/home/dror/vsp/vets-website/src/site/stages/build/drupal/metalsmith-drupal.js:270:7)
TypeError: Cannot read property 'entities' of undefined
    at createPastEventListPages (/home/dror/vsp/vets-website/src/site/stages/build/drupal/health-care-region.js:39:13)
    at pipeDrupalPagesIntoMetalsmith (/home/dror/vsp/vets-website/src/site/stages/build/drupal/metalsmith-drupal.js:130:9)
    at Ware.<anonymous> (/home/dror/vsp/vets-website/src/site/stages/build/drupal/metalsmith-drupal.js:270:7)
```

**Comment by swirtSJW** [comment]
@drorva Can you give me a node id or uuid for a node that is giving you this error?

**Comment by drorva** [comment]
Actually, this might be a result of missing transformers, so let's put it on the back burner for now.

**Comment by cvalarida** [comment]
Theo's working on https://github.com/department-of-veterans-affairs/va.gov-team/issues/11862, which is essentially the same. It's the result of a missing reverse field, which are available now. Closing this in favor of the other one.
