### ISSUE TITLE
Warning in moment.js during "Step 19: Apply layouts"

### ISSUE THREAD

**Issue by drorva** [department-of-veterans-affairs/va.gov-team#11643]
We're getting the following exception
```
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFCArguments: te formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
[0] _isAMomentObject: true, _isUTC: true, _useUTC: true, _l: undefined, _i: 5/30/2019, 5:00:00 PM, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (/home/dror/tmp/build-vw/node_modules/moment/moment.js:320:98)
    at configFromString (/home/dror/tmp/build-vw/node_modules/moment/moment.js:2385:15)
    at configFromInput (/home/dror/tmp/build-vw/node_modules/moment/moment.js:2611:13)
    at prepareConfig (/home/dror/tmp/build-vw/node_modules/moment/moment.js:2594:13)
    at createFromConfig (/home/dror/tmp/build-vw/node_modules/moment/moment.js:2561:44)
    at createLocalOrUTC (/home/dror/tmp/build-vw/node_modules/moment/moment.js:2648:16)
    at Function.createUTC [as utc] (/home/dror/tmp/build-vw/node_modules/moment/moment.js:88:16)
    at prettyTimeFormatted (/home/dror/tmp/build-vw/src/site/filters/liquid.js:23:25)
    at liquid.filters.timeZone (/home/dror/tmp/build-vw/src/site/filters/liquid.js:32:14)
    at exports.Context.callFilter (/home/dror/tmp/build-vw/node_modules/tinyliquid/lib/context.js:387:28)
    at /home/dror/tmp/build-vw/node_modules/tinyliquid/lib/vm.js:312:15
    at next (/home/dror/tmp/build-vw/node_modules/tinyliquid/lib/utils.js:492:9)
    at /home/dror/tmp/build-vw/node_modules/tinyliquid/lib/vm.js:95:9
    at exports.run (/home/dror/tmp/build-vw/node_modules/tinyliquid/lib/vm.js:66:5)
    at /home/dror/tmp/build-vw/node_modules/tinyliquid/lib/vm.js:90:5
    at next (/home/dror/tmp/build-vw/node_modules/tinyliquid/lib/utils.js:490:9)
```

**Comment by ElijahLynn** [comment]
fwiw, this is an issue with the current build process, unrelated to CMS Export. I think it should be removed from this epic. Also, @cvalarida had provided me some verbal context on this once and said it was a non-trivial fix, I believe.

**Comment by ElijahLynn** [comment]
Related > (internal) https://dsva.slack.com/archives/C0MQ281DJ/p1586271155027900

**Comment by timwright12** [comment]
@meganhkelley This was fixed during a maintenance ticket about a month ago. We do still have a deprecation warning in the "apply layouts" step, but it's because of the [metalsmith-layouts](https://github.com/metalsmith/metalsmith-layouts) plugin.

We have a separate ticket for that because it's a third party dependency upgrade https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/18045
