### ISSUE TITLE
Missing pastEvents on node-event_listing

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#11868]
## Issue Description
When performing a `vagovprod` CMS export build, after skipping the error
captured in #11862, I'm running into the following error:
```
TypeError: Cannot read property 'entities' of undefined
    at createPastEventListPages (/home/christopher/adhoc/vets-website/src/site/stages/build/drupal/health-care-region.js:40:13)
    at pipeDrupalPagesIntoMetalsmith (/home/christopher/adhoc/vets-website/src/site/stages/build/drupal/metalsmith-drupal.js:129:7)
    at Ware.<anonymous> (/home/christopher/adhoc/vets-website/src/site/stages/build/drupal/metalsmith-drupal.js:264:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Tracing it back, this is because the `node-event_listing` has no `pastEvents`.

Two things need to be addressed here:
1. The transformer needs to be created for `node-event_listing`
    - Old PR for this can be found at https://github.com/department-of-veterans-affairs/vets-website/pull/11543/files
    - This will likely need updating
2. The `pastEvents` field needs to be present in the `node-event_listing`
   bundles
    - ...I actually don't know how to get here yet. Steve made a
      `reverse_field_list`, but I don't know that it solves our problem like we
      want it to, since, if I understand it correctly, it'll contain all
      "reverse fields," but some bundles like the `health_care_region_page` have
      many `reverseFieldOfficeNode` queries in the GraphQL query.

**Comment by meganhkelley** [comment]
No longer relevant due to pivot away from CMS export, documented in #20165
