### ISSUE TITLE
Update build script to use S3 cache for CMS DEV/STAGING more reliably OR PROD

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-team#16220]
The vets-website build script that is running on PRs and deployment tests and is causing some PRs to fail the tests. The build script used to detect deployments to CMS DEV/STAGING and fallback to a previous builds S3 cache if it was down. This no longer seems to be working and might have something to do with the CMS launching a "deploy mode" notifies editors/users that a deploy is in progress. 

The actual step failing is:

> [2020-11-16T18:14:31.641Z] yarn run v1.22.5
> 
> [2020-11-16T18:14:31.641Z] $ node --max-old-space-size=8192 script/build-content.js --buildtype=vagovstaging --asset-source=local --drupal-address=http://internal-dsva-vagov-staging-cms-1188006.us-gov-west-1.elb.amazonaws.com --pull-drupal
> 
> [2020-11-16T18:14:31.641Z] Pulling feature flags from Drupal...
> [2020-11-16T18:14:31.641Z] /application/src/site/stages/build/plugins/download-assets.js:14
> [2020-11-16T18:14:31.641Z]   throw up;
> [2020-11-16T18:14:31.641Z]   ^
> [2020-11-16T18:14:31.641Z] 
> [2020-11-16T18:14:31.641Z] TypeError: Could not parse Drupal build flags. Response:
> [2020-11-16T18:14:31.641Z] <!DOCTYPE html>
> [2020-11-16T18:14:31.641Z] <html>
> [2020-11-16T18:14:31.641Z] <head>
> [2020-11-16T18:14:31.641Z]   <title>System update in progress</title>
> [2020-11-16T18:14:31.641Z] <style>
> [2020-11-16T18:14:31.641Z]     body {
> [2020-11-16T18:14:31.641Z]         font-style: normal;

We can set these all to use PROD or fix the S3 cache pull condition. 

(internal) https://dsva.slack.com/archives/CDHBKAL9W/p1605551630045000

**Comment by meganhkelley** [comment]
We believe this will be resolved with the release of content build separation (epic #2719)

**Comment by ElijahLynn** [comment]
Also seeing the failure on "pulling side nav menus from drupal":

> Step 3 of 36 start: Get Drupal content

[2020-11-17T16:40:20.786Z] Drupal content unavailable in local cache: /application/.cache/vagovdev/drupal/pages.json

[2020-11-17T16:40:20.786Z] Attempting to load Drupal content from API at http://internal-dsva-vagov-dev-cms-812329399.us-gov-west-1.elb.amazonaws.com

[2020-11-17T16:40:20.786Z] Pulling side nav menus from Drupal...

[2020-11-17T16:43:57.153Z] There was an error parsing the response body, it isn't valid JSON. Here is the error:

[2020-11-17T16:43:57.153Z] SyntaxError: Unexpected token < in JSON at position 0

[2020-11-17T16:43:57.153Z]     at JSON.parse (<anonymous>)

[2020-11-17T16:43:57.153Z]     at /application/src/site/stages/build/drupal/****.js:96:25

[2020-11-17T16:43:57.153Z]     at processTicksAndRejections (internal/process/task_queues.js:93:5)

[2020-11-17T16:43:57.153Z]     at async getContentViaGraphQL (/application/src/site/stages/build/drupal/metalsmith-drupal.js:208:19)

[2020-11-17T16:43:57.153Z]     at async loadDrupal (/application/src/site/stages/build/drupal/metalsmith-drupal.js:277:7)

[2020-11-17T16:43:57.153Z]     at async Ware.<anonymous> (/application/src/site/stages/build/drupal/metalsmith-drupal.js:319:20)

[2020-11-17T16:43:57.153Z] 

[2020-11-17T16:43:57.153Z] Response code: 200

[2020-11-17T16:43:57.153Z] Start of body: <!DOCTYPE html>

[2020-11-17T16:43:57.153Z] <html lang="en" dir="ltr" prefix="content: http://purl.org/rss/1.0/modules/content/ 

[2020-11-17T16:43:57.153Z] End of body:    

[2020-11-17T16:43:57.153Z]     <script src="/core/themes/seven/js/mobile.install.js?v=8.8.10"></script>

[2020-11-17T16:43:57.153Z] 

[2020-11-17T16:43:57.153Z]   </body>

[2020-11-17T16:43:57.153Z] </html>

[2020-11-17T16:43:57.153Z] 

[2020-11-17T16:43:57.153Z] SyntaxError: Unexpected token < in JSON at position 0

[2020-11-17T16:43:57.153Z]     at JSON.parse (<anonymous>)

[2020-11-17T16:43:57.153Z]     at /application/src/site/stages/build/drupal/****.js:96:25

[2020-11-17T16:43:57.153Z]     at processTicksAndRejections (internal/process/task_queues.js:93:5)

[2020-11-17T16:43:57.153Z]     at async getContentViaGraphQL (/application/src/site/stages/build/drupal/metalsmith-drupal.js:208:19)

[2020-11-17T16:43:57.153Z]     at async loadDrupal (/application/src/site/stages/build/drupal/metalsmith-drupal.js:277:7)

[2020-11-17T16:43:57.153Z]     at async Ware.<anonymous> (/application/src/site/stages/build/drupal/metalsmith-drupal.js:319:20)

[2020-11-17T16:43:57.153Z] Failed to pipe Drupal content into Metalsmith!

[2020-11-17T16:43:57.153Z] /application/src/site/stages/build/index.js:280

[2020-11-17T16:43:57.153Z]     if (err) throw err;

[2020-11-17T16:43:57.153Z]              ^

[2020-11-17T16:43:57.153Z] 

[2020-11-17T16:43:57.153Z] SyntaxError: Unexpected token < in JSON at position 0

[2020-11-17T16:43:57.153Z]     at JSON.parse (<anonymous>)

[2020-11-17T16:43:57.153Z]     at /application/src/site/stages/build/drupal/****.js:96:25

[2020-11-17T16:43:57.153Z]     at processTicksAndRejections (internal/process/task_queues.js:93:5)

[2020-11-17T16:43:57.153Z]     at async getContentViaGraphQL (/application/src/site/stages/build/drupal/metalsmith-drupal.js:208:19)

[2020-11-17T16:43:57.153Z]     at async loadDrupal (/application/src/site/stages/build/drupal/metalsmith-drupal.js:277:7)

[2020-11-17T16:43:57.153Z]     at async Ware.<anonymous> (/application/src/site/stages/build/drupal/metalsmith-drupal.js:319:20)

[2020-11-17T16:43:57.153Z] error Command failed with exit code 1.

[2020-11-17T16:43:57.153Z] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[2020-11-17T16:43:57.153Z] npm ERR! code ELIFECYCLE

**Comment by ElijahLynn** [comment]
> We believe this will be resolved with the release of content build separation (epic #2719)

Nice to hear! Thanks

**Comment by mpelzsherman** [comment]
This continues to happen quite often. Can we do anything in the short term to address this?

**Comment by mpelzsherman** [comment]
Here is the error we see when the builds fail due to a CMS system update in progress:

```
[2020-12-04T17:39:12.358Z] $ node --max-old-space-size=8192 script/build-content.js --buildtype=vagovstaging --asset-source=local --drupal-address=http://internal-dsva-vagov-staging-cms-1188006.us-gov-west-1.elb.amazonaws.com
[2020-12-04T17:39:12.358Z] Pulling feature flags from Drupal...
[2020-12-04T17:39:12.358Z] /application/src/site/stages/build/plugins/download-assets.js:14
[2020-12-04T17:39:12.358Z]   throw up;
[2020-12-04T17:39:12.358Z]   ^
[2020-12-04T17:39:12.358Z] 
[2020-12-04T17:39:12.358Z] TypeError: Could not parse Drupal build flags. Response:
[2020-12-04T17:39:12.358Z] <!DOCTYPE html>
[2020-12-04T17:39:12.358Z] <html>
[2020-12-04T17:39:12.358Z] <head>
[2020-12-04T17:39:12.358Z]   <title>System update in progress</title>
[2020-12-04T17:39:12.358Z] <style>
```

**Comment by mpelzsherman** [comment]
Assigning to @U-DON per [Slack convo.](https://dsva.slack.com/archives/CDHBKAL9W/p1607372724173200?thread_ts=1607363447.158700&cid=CDHBKAL9W)

**Comment by U-DON** [comment]
Builds have been updated to pull from prod CMS.
https://github.com/department-of-veterans-affairs/vets-website/pull/15118

After merging in or branching off of the latest master, let us know if builds still fail due to system update errors.
