### ISSUE TITLE
Facility Locator breaks on resize

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#1693]
Under certain conditions, the Facility Locator will break when resizing the window.

1. Go to: https://www.va.gov/find-locations/?address=97130&context=Manzanita%2C%20Oregon%2097130%2C%20United%20States&facilityType=all&location=45.763690956618674%2C-123.94088745117189&page=1&serviceType&zoomLevel=9
2. Click on one of the location markers on the map
3. Shrink the window vertically
4. The entire react app will stop rendering

GIF of bug:

![crash](https://user-images.githubusercontent.com/20728956/64712670-796b1f80-d470-11e9-8896-7d10b17da85d.gif)

The console reports the following errors:

```
Invariant Violation: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:136757
    at a (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:136860)
    at Za (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:231589)
    at Object.enqueueSetState (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:181080)
    at u.w.setState (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:115910)
    at u.l.onStateChange (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:11591)
    at y (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:39691)
    at https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/facilities.entry.2e7f3a4ed71aaf88cc9a-1568139413663.js:1:221706
    at https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:66604
    at Object.updateSearchQuery (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:41714)
    at t.<anonymous> (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/facilities.entry.2e7f3a4ed71aaf88cc9a-1568139413663.js:1:789897)
    at t.fire (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/facilities.entry.2e7f3a4ed71aaf88cc9a-1568139413663.js:1:33452)
    at t._onPanTransitionEnd (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/facilities.entry.2e7f3a4ed71aaf88cc9a-1568139413663.js:1:72981)
    at t.fire (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/facilities.entry.2e7f3a4ed71aaf88cc9a-1568139413663.js:1:33452)
    at t._complete (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/facilities.entry.2e7f3a4ed71aaf88cc9a-1568139413663.js:1:54367)
    at t.stop (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/facilities.entry.2e7f3a4ed71aaf88cc9a-1568139413663.js:1:53947)
    at t._adjustPan (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/facilities.entry.2e7f3a4ed71aaf88cc9a-1568139413663.js:1:122517)
    at t.update (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/facilities.entry.2e7f3a4ed71aaf88cc9a-1568139413663.js:1:118990)
    at t.n.componentDidUpdate (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/facilities.entry.2e7f3a4ed71aaf88cc9a-1568139413663.js:1:776587)
    at Wa (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:218819)
    at Ha (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:221395)
    at https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:234602
    at Object.t.unstable_runWithPriority (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:4150)
    at Nu (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:234537)
    at ju (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:234313)
    at Cu (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:233658)
    at Eu (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:232679)
    at Za (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:231553)
    at Object.enqueueSetState (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:181080)
    at u.w.setState (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:115910)
    at u.l.onStateChange (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:11591)
    at y (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:39691)
    at https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/facilities.entry.2e7f3a4ed71aaf88cc9a-1568139413663.js:1:221706
    at https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:66604
    at Object.updateSearchQuery (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:41714)
    at t.<anonymous> (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/facilities.entry.2e7f3a4ed71aaf88cc9a-1568139413663.js:1:789897)
    at t.fire (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/facilities.entry.2e7f3a4ed71aaf88cc9a-1568139413663.js:1:33452)
    at r (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:121334)
(anonymous) @ breadcrumbs.js:58
r @ backend.js:1
pa @ react-dom.production.min.js:198
n.callback @ react-dom.production.min.js:210
oa @ react-dom.production.min.js:193
ra @ react-dom.production.min.js:193
Wa @ react-dom.production.min.js:217
Ha @ react-dom.production.min.js:220
(anonymous) @ react-dom.production.min.js:250
t.unstable_runWithPriority @ scheduler.production.min.js:18
Nu @ react-dom.production.min.js:250
ju @ react-dom.production.min.js:249
Cu @ react-dom.production.min.js:248
Eu @ react-dom.production.min.js:245
Za @ react-dom.production.min.js:243
enqueueSetState @ react-dom.production.min.js:130
w.setState @ react.production.min.js:13
l.onStateChange @ connectAdvanced.js:205
y @ redux.js:220
(anonymous) @ analytics-middleware.js:24
(anonymous) @ index.js:14
(anonymous) @ redux.js:475
(anonymous) @ VAMap.jsx:348
fire @ leaflet-src.js:593
r @ helpers.js:70
setTimeout (async)
(anonymous) @ trycatch.js:28
invalidateSize @ leaflet-src.js:3598
(anonymous) @ leaflet-src.js:4336
r @ helpers.js:70
requestAnimationFrame (async)
(anonymous) @ trycatch.js:34
C @ leaflet-src.js:244
_onResize @ leaflet-src.js:4335
i @ leaflet-src.js:2661
r @ helpers.js:70
react-dom.production.min.js:13 Uncaught Invariant Violation: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:136757
    at a (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:136860)
    at Za (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:231589)
    at Object.enqueueSetState (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:181080)
    at u.w.setState (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:115910)
    at u.l.onStateChange (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:11591)
    at y (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:39691)
    at https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/facilities.entry.2e7f3a4ed71aaf88cc9a-1568139413663.js:1:221706
    at https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:66604
    at Object.updateSearchQuery (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:41714)
    at t.<anonymous> (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/facilities.entry.2e7f3a4ed71aaf88cc9a-1568139413663.js:1:789897)
    at t.fire (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/facilities.entry.2e7f3a4ed71aaf88cc9a-1568139413663.js:1:33452)
    at t._onPanTransitionEnd (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/facilities.entry.2e7f3a4ed71aaf88cc9a-1568139413663.js:1:72981)
    at t.fire (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/facilities.entry.2e7f3a4ed71aaf88cc9a-1568139413663.js:1:33452)
    at t._complete (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/facilities.entry.2e7f3a4ed71aaf88cc9a-1568139413663.js:1:54367)
    at t.stop (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/facilities.entry.2e7f3a4ed71aaf88cc9a-1568139413663.js:1:53947)
    at t._adjustPan (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/facilities.entry.2e7f3a4ed71aaf88cc9a-1568139413663.js:1:122517)
    at t.update (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/facilities.entry.2e7f3a4ed71aaf88cc9a-1568139413663.js:1:118990)
    at t.n.componentDidUpdate (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/facilities.entry.2e7f3a4ed71aaf88cc9a-1568139413663.js:1:776587)
    at Wa (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:218819)
    at Ha (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:221395)
    at https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:234602
    at Object.t.unstable_runWithPriority (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:4150)
    at Nu (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:234537)
    at ju (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:234313)
    at Cu (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:233658)
    at Eu (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:232679)
    at Za (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:231553)
    at Object.enqueueSetState (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:181080)
    at u.w.setState (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:115910)
    at u.l.onStateChange (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:11591)
    at y (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:39691)
    at https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/facilities.entry.2e7f3a4ed71aaf88cc9a-1568139413663.js:1:221706
    at https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:66604
    at Object.updateSearchQuery (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:41714)
    at t.<anonymous> (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/facilities.entry.2e7f3a4ed71aaf88cc9a-1568139413663.js:1:789897)
    at t.fire (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/facilities.entry.2e7f3a4ed71aaf88cc9a-1568139413663.js:1:33452)
    at r (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1:121334)
(anonymous) @ react-dom.production.min.js:13
a @ react-dom.production.min.js:14
Za @ react-dom.production.min.js:243
enqueueSetState @ react-dom.production.min.js:130
w.setState @ react.production.min.js:13
l.onStateChange @ connectAdvanced.js:205
y @ redux.js:220
(anonymous) @ analytics-middleware.js:24
(anonymous) @ index.js:14
(anonymous) @ redux.js:475
(anonymous) @ VAMap.jsx:348
fire @ leaflet-src.js:593
_onPanTransitionEnd @ leaflet-src.js:4582
fire @ leaflet-src.js:593
_complete @ leaflet-src.js:3000
stop @ leaflet-src.js:2961
_adjustPan @ leaflet-src.js:9871
update @ leaflet-src.js:9528
n.componentDidUpdate @ DivOverlay.js:52
Wa @ react-dom.production.min.js:216
Ha @ react-dom.production.min.js:220
(anonymous) @ react-dom.production.min.js:250
t.unstable_runWithPriority @ scheduler.production.min.js:18
Nu @ react-dom.production.min.js:250
ju @ react-dom.production.min.js:249
Cu @ react-dom.production.min.js:248
Eu @ react-dom.production.min.js:245
Za @ react-dom.production.min.js:243
enqueueSetState @ react-dom.production.min.js:130
w.setState @ react.production.min.js:13
l.onStateChange @ connectAdvanced.js:205
y @ redux.js:220
(anonymous) @ analytics-middleware.js:24
(anonymous) @ index.js:14
(anonymous) @ redux.js:475
(anonymous) @ VAMap.jsx:348
fire @ leaflet-src.js:593
r @ helpers.js:70
setTimeout (async)
(anonymous) @ trycatch.js:28
invalidateSize @ leaflet-src.js:3598
(anonymous) @ leaflet-src.js:4336
r @ helpers.js:70
requestAnimationFrame (async)
(anonymous) @ trycatch.js:34
C @ leaflet-src.js:244
_onResize @ leaflet-src.js:4335
i @ leaflet-src.js:2661
r @ helpers.js:70
Show 8 more frames
vendor.entry.6058e0d9a4a00157ba30-1568139413663.js:1 [Violation] 'setTimeout' handler took 639ms
[Violation] Forced reflow while executing JavaScript took 267ms
51helpers.js:86 Uncaught TypeError: Cannot read property 'classList' of undefined
    at dt (leaflet-src.js:2337)
    at t._onPanTransitionEnd (leaflet-src.js:4581)
    at t.fire (leaflet-src.js:593)
    at t._complete (leaflet-src.js:3000)
    at t._step (leaflet-src.js:2978)
    at t._animate (leaflet-src.js:2967)
    at r (helpers.js:70)
dt @ leaflet-src.js:2337
_onPanTransitionEnd @ leaflet-src.js:4581
fire @ leaflet-src.js:593
_complete @ leaflet-src.js:3000
_step @ leaflet-src.js:2978
_animate @ leaflet-src.js:2967
r @ helpers.js:70
requestAnimationFrame (async)
(anonymous) @ trycatch.js:34
C @ leaflet-src.js:244
_animate @ leaflet-src.js:2966
run @ leaflet-src.js:2952
panBy @ leaflet-src.js:3341
_adjustPan @ leaflet-src.js:9909
update @ leaflet-src.js:9528
n.componentDidUpdate @ DivOverlay.js:52
Wa @ react-dom.production.min.js:216
Ha @ react-dom.production.min.js:220
(anonymous) @ react-dom.production.min.js:250
t.unstable_runWithPriority @ scheduler.production.min.js:18
Nu @ react-dom.production.min.js:250
ju @ react-dom.production.min.js:249
Cu @ react-dom.production.min.js:248
Eu @ react-dom.production.min.js:245
Za @ react-dom.production.min.js:243
enqueueSetState @ react-dom.production.min.js:130
w.setState @ react.production.min.js:13
l.onStateChange @ connectAdvanced.js:205
y @ redux.js:220
(anonymous) @ analytics-middleware.js:24
(anonymous) @ index.js:14
(anonymous) @ redux.js:475
(anonymous) @ VAMap.jsx:348
fire @ leaflet-src.js:593
r @ helpers.js:70
setTimeout (async)
(anonymous) @ trycatch.js:28
invalidateSize @ leaflet-src.js:3598
(anonymous) @ leaflet-src.js:4336
r @ helpers.js:70
requestAnimationFrame (async)
(anonymous) @ trycatch.js:34
C @ leaflet-src.js:244
_onResize @ leaflet-src.js:4335
i @ leaflet-src.js:2661
r @ helpers.js:70
mapHelpers.js:53 Uncaught (in promise) TypeError: Cannot read property 'place_name' of undefined
    at mapHelpers.js:53
    at w (runtime.js:62)
    at Generator._invoke (runtime.js:288)
    at Generator.e.<computed> [as next] (runtime.js:114)
    at B (MapboxClient.js:4)
    at a (mapHelpers.js:49)
```

**Comment by mmiddaugh** [comment]
@brangi here is one to evaluate for level of effort and impact for users

**Comment by brangi** [comment]
@erikphansen  I came across this issue on MapBox https://github.com/mapbox/mapbox-gl-js/issues/8669, could be related.

**Comment by mmiddaugh** [comment]
Decided to hold this one pending upgrade of Mapbox in the next sprint.

**Comment by mmiddaugh** [comment]
Pending more information on Mapbox service.
Need to move forward by mid-November

**Comment by mmiddaugh** [comment]
**Acceptance criteria:**
This criteria is true regardless of facility type chosen.
User interaction with map does not cause page to fail. 
When user clicks on map icon, the user can view a hover over containing the name and type of facility. 
When user clicks on the name displayed within the hover bubble, the user is taken to the relevant facility detail page.

**Comment by mmiddaugh** [comment]
Please see observations in [#1694]

**Comment by mmiddaugh** [comment]
Will revisit after MVP redesign

**Comment by mmiddaugh** [comment]
This will be resolved with redesign as pop-ups will no longer be present.
