### ISSUE TITLE
Periodically failing vets-api build : ActiveRecord::NoEnvironmentInSchemaError

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#2365]
Connects: https://github.com/department-of-veterans-affairs/va.gov-team/issues/2295

## The Problem
`gibct-data-service` jobs will occasionally fail with 
```
rails aborted!
ActiveRecord::NoEnvironmentInSchemaError: 

Environment data not found in the schema. To resolve this issue, run: 

        bin/rails db:environment:set RAILS_ENV=test

/usr/local/bundle/gems/activerecord-5.0.7.2/lib/active_record/migration.rb:1274:in `last_stored_environment'
/usr/local/bundle/gems/activerecord-5.0.7.2/lib/active_record/tasks/database_tasks.rb:48:in `check_protected_environments!'
/usr/local/bundle/gems/activerecord-5.0.7.2/lib/active_record/railties/databases.rake:11:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/activerecord-5.0.7.2/lib/active_record/railties/databases.rake:252:in `block (3 levels) in <top (required)>'
/usr/local/bundle/gems/railties-5.0.7.2/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/usr/local/bundle/gems/railties-5.0.7.2/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/usr/local/bundle/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/usr/local/bundle/gems/railties-5.0.7.2/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:schema:load => db:check_protected_environments
```

[Slack conversation](https://dsva.slack.com/archives/CBU0KDSB1/p1570645577008500)

**Comment by omgitsbillryan** [comment]
The resolution was to kill stale docker containers running on the particular jenkins swarm node.

**Comment by alexpappasoddball** [comment]
@omgitsbillryan can we close this one?

**Comment by johnpaulashenfelter** [comment]
Closing due to inactivity AND seems like it was solved
