### ISSUE TITLE
Upgrade Nightwatch from 0.9 to 1.x

### ISSUE THREAD

**Issue by billfienberg** [department-of-veterans-affairs/va.gov-team#23695]
Version 1.4 of Nightwatch claims to improve network stability and performance. 

>This version significantly improves the network stability and performance of the test runner, by improving the underlying http retry mechanism and error detection and reporting of API commands – a particularly important update for when using cloud testing services. - https://github.com/nightwatchjs/nightwatch/releases/tag/v1.4.0

[We're currently using `nightwatch@0.9.21`](https://github.com/department-of-veterans-affairs/vets-website/blob/4ebb0a9a79733ccb4731ebdd16ffded7e8e09175/yarn.lock#L13515-L13529) and the [latest release](https://github.com/nightwatchjs/nightwatch/releases) is `1.6.3`. 

Perhaps we should try upgrading from major version `0` to` major version `1`. 

## Links

- [PR from June 2020 to upgrade from 0.9.16 to 0.9.21](https://github.com/department-of-veterans-affairs/vets-website/pull/13066)
- [Release notes for `nightwatch@1.0.1`](https://github.com/nightwatchjs/nightwatch/releases/tag/v1.0.1)
- [Release notes for `nightwatch@1.1.0](https://github.com/nightwatchjs/nightwatch/releases/tag/v1.1.0)
- [Release notes for `nightwatch@1.2.1](https://github.com/nightwatchjs/nightwatch/releases/tag/v1.2.1)
- [Release notes for `nightwatch@1.3.0](https://github.com/nightwatchjs/nightwatch/releases/tag/v1.3.0)
- [Release notes for `nightwatch@1.4.0](https://github.com/nightwatchjs/nightwatch/releases/tag/v1.4.0)
- [Release notes for `nightwatch@1.5.0](https://github.com/nightwatchjs/nightwatch/releases/tag/v1.5.0)
- [Release notes for `nightwatch@1.6.0](https://github.com/nightwatchjs/nightwatch/releases/tag/v1.6.0)
- [Migrating to Nightwatch 1.0](https://github.com/nightwatchjs/nightwatch/wiki/Migrating-to-Nightwatch-1.0)

## Branches

- [`upgrade-nightwatch-from-0.9-to-1.x`](https://github.com/department-of-veterans-affairs/vets-website/compare/upgrade-nightwatch-from-0.9-to-1.x)

**Comment by billfienberg** [comment]
There are currently [four failing tests](http://jenkins.vfs.va.gov/blue/organizations/jenkins/testing%2Fvets-website/detail/upgrade-nightwatch-from-0.9-to-1.x/8/tests) on my [branch](https://github.com/department-of-veterans-affairs/vets-website/compare/upgrade-nightwatch-from-0.9-to-1.x).

![image](https://user-images.githubusercontent.com/6130520/115887823-ed74f400-a417-11eb-8d9b-74c7a2c0e849.png)


#### `applications.edu-benefits.tests.feedback-tool.01.feedback-tool-keyboard.e2e.spec`

```
Error
Error while running "value" command: Testing if value of element [0;33m<#root_fullName_prefix>[0m equals [0;33m'Dr.'[0m in 5000ms - expected [0;32m"equals 'Dr.'"[0m but got: [0;31m"element could not be located"[0m [0;90m(5131ms)[0m
Stacktrace
at NightwatchAPI.assertCorrectOptionIsSelected (/application/src/platform/testing/e2e/nightwatch-commands/allyEvaluateSelectMenu.js:44:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

#### `applications.gi.tests.e2e.01-keyboard.e2e.spec`

```
Error
Error while running "value" command: Testing if value of element [0;33m<#militaryStatus>[0m equals [0;33m'child'[0m in 5000ms - expected [0;32m"equals 'child'"[0m but got: [0;31m"element could not be located"[0m [0;90m(5130ms)[0m
Stacktrace
at NightwatchAPI.assertCorrectOptionIsSelected (/application/src/platform/testing/e2e/nightwatch-commands/allyEvaluateSelectMenu.js:44:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

#### `applications.pensions.tests.00-all-fields.e2e.spec`

```
Error
Timed out while waiting for element <input#root_files> to be visible for 5000 milliseconds. - expected "visible" but got: "not visible" (5100ms)
Stacktrace
at beginApplication (/application/src/applications/pensions/tests/00-all-fields.e2e.spec.js:630:12)
    at Object.BeginApplication [as Begin application] (/application/src/platform/testing/e2e/helpers.js:106:7)
    at runMicrotasks (<anonymous>)
```

#### `platform.testing.e2e.megamenu.megamenu.e2e.spec`

```
Error
Error while running "elements" command: expected 4 to equal 3 - expected "3" but got: "4"
Stacktrace
AssertionError: Error while running &#34;elements&#34; command: expected 4 to equal 3 - expected &#34;3&#34; but got: &#34;4&#34;
    at Object.&lt;anonymous&gt; (/application/src/platform/testing/e2e/megamenu/megamenu.js:110:48)
    at makePromise (/application/node_modules/nightwatch/lib/utils/index.js:136:28)
    at /application/node_modules/nightwatch/lib/api/protocol/_base-action.js:103:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by billfienberg** [comment]
`src/applications/pensions/tests/00-all-fields.e2e.spec.js` is one long test (2m 10s). 

![image](https://user-images.githubusercontent.com/6130520/116081464-e8a28100-a65f-11eb-9677-00b76ddccf73.png)

**Comment by billfienberg** [comment]
I think I found a strange bug in src/platform/forms-system/src/js/widgets/CurrencyWidget.jsx on `/pension/application/527EZ/financial-disclosure/monthly-income`. It appears that the following values are invalid: 

- `0.0010`
- `0.0020`
- `0.0030`
- `0.0040`
- `0.0050`
- `0.0060`
- `0.0070`
- `0.0080`
- `0.0090`

![image](https://user-images.githubusercontent.com/6130520/116082681-4edbd380-a661-11eb-802a-4ea269f7f398.png)

I found the bug while trying to fix a failing nightwatch test. The test was appending the values from the test data (src/applications/pensions/tests/schema/maximal-test.json). I assume the test should replace the input value instead of appending to it.

**Comment by billfienberg** [comment]
I think I found a strange bug in src/platform/forms-system/src/js/widgets/CurrencyWidget.jsx on `/pension/application/527EZ/financial-disclosure/monthly-income`. It appears that the following values are invalid: 

- `0.0010`
- `0.0020`
- `0.0030`
- `0.0040`
- `0.0050`
- `0.0060`
- `0.0070`
- `0.0080`
- `0.0090`

![image](https://user-images.githubusercontent.com/6130520/116082681-4edbd380-a661-11eb-802a-4ea269f7f398.png)

I found the bug while trying to fix a failing nightwatch test. The test was appending the values from the test data (src/applications/pensions/tests/schema/maximal-test.json). I assume the test should replace the input value instead of appending to it.

**Comment by cvalarida** [comment]
There's a Nightwatch helper that's supposed to clear the inputs before adding the data to it. Looks like the upgraded version isn't clearing the inputs as expected before inserting the new values. This may be unique to the currency widget, but I couldn't tell you why that might be off the top of my head.

**Comment by billfienberg** [comment]
Branch for new attempt (post-Content Build Separation): https://github.com/department-of-veterans-affairs/vets-website/compare/upgrade-nightwatch-major-version

Related thread in #vsp-tools-fe: https://dsva.slack.com/archives/CQH357ZTP/p1620692712302200

**Comment by pjhill** [comment]
OBE
