### ISSUE TITLE
Fix '.github/workflows/main.yml: All jobs have failed' error

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#27046]
I woke up to this email from GitHub:

![image](https://user-images.githubusercontent.com/9326247/124817992-7cce7580-df38-11eb-84df-e2d39eab2052.png)

The error:

```
Error: Cannot read property 'forEach' of undefined
Error TypeError: Cannot read property 'forEach' of undefined
    at Object.tests (/home/runner/work/testing-tools-team-dashboard-data/testing-tools-team-dashboard-data/src/testrail/createTable.js:76:13)
    at async run (/home/runner/work/testing-tools-team-dashboard-data/testing-tools-team-dashboard-data/src/testrail/index.js:14:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

For some reason `tests`, which is an array, sometimes has a value of `undefined`.

```js
      tests.forEach(test => {
        if (!test.custom_steps_separated) {
          // BigQuery throws an error if 'test.custom_steps_separated' is null
          // because the mode for the field is 'REPEATED'.
          // Setting it to an empty array so the record can be inserted.
          test.custom_steps_separated = [];
        }
      });
```

I added a check to make sure `tests` exist:

```js
      if (tests) {
        tests.forEach(test => {
          if (!test.custom_steps_separated) {
            // BigQuery throws an error if 'test.custom_steps_separated' is null
            // because the mode for the field is 'REPEATED'.
            // Setting it to an empty array so the record can be inserted.
            test.custom_steps_separated = [];
          }
        });
        
        rows.push(...tests);
      }
```

I added checks for other arrays too.

PR - https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/pull/43

**Comment by holdenhinkle** [comment]
I found the source of the error by adding the following `console.log()` statements to `getRows()` in `src/testrail/service.js`:

```javascript
        // The following is for debugging purposes
        // I'm trying to track down a bug that appears 1x every 1-2 weeks
        if (data.body === undefined) {
          console.log(`Alert: data.body from calling ${fn} is undefined`);
          console.log(`${fn} response: ${data}`);

          Object.keys(data).forEach(prop => {
            console.log('Prop: ', prop);
            console.log('Value: ', data[prop]);
          });
        }
```

The following was logged many times when I ran the job:

```javascript
Alert: data.body from calling async function getResults(testId, filters) {
    return await callApi('getResults', testId, filters);
  } is undefined
async function getResults(testId, filters) {
    return await callApi('getResults', testId, filters);
  } response: [object Object]
Prop:  message
Value:  { error: 'Request timed out' }
```

So the issue is a timeout.

Handling it:

```javascript
      while (hitRateLimit(data.response.statusCode) || data.message.error === 'Request timed out') {
        if (hitRateLimit(data.response.statusCode)) {
          const retryAfterSeconds = Number(data.response.headers['retry-after']);
          console.log("Error: 'API Rate Limit Exceeded'");
          console.log(`Waiting ${retryAfterSeconds} seconds...`);
          await new Promise(resolve => setTimeout(resolve, retryAfterSeconds * 1000));
          await callGetFn();
        } else {
          console.log("Error: 'Request timed out'");
          await callGetFn();
        }
      }
```

It's complaining about `data.message.error`. Running another job, logging out data as json to see what's going on - https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/runs/3015677726?check_suite_focus=true


```js
        if (data.body === undefined) {
          console.log(`Alert: data.body from calling ${fn} is undefined`);
          console.log('JSON: ', JSON.stringify(data));
        }
```

I'm going to bed. I'll finish this in the morning...

**Comment by holdenhinkle** [comment]
There are two messages, with response status code `500`:

```
JSON:  {"message":{"error":"Underlying connection error: Connection timeout"},"response":{"statusCode":500,"body":"{\"error\":\"Underlying connection error: Connection timeout\"}","headers":{"date":"Thu, 08 Jul 2021 05:10:47 GMT","content-type":"application/json; charset=utf-8","content-length":"59","connection":"close","server":"Apache","access-control-allow-headers":"authorization, content-type, x-api-ident","access-control-allow-origin":"https://testrail-lite.testrail.io","vary":"Origin"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"dsvavsp.testrail.io","port":443,"hostname":"dsvavsp.testrail.io","hash":null,"search":"?/api/v2/get_results/14878&offset=0&limit=250","query":"/api/v2/get_results/14878&offset=0&limit=250","pathname":"/index.php","path":"/index.php?/api/v2/get_results/14878&offset=0&limit=250","href":"https://dsvavsp.testrail.io/index.php?/api/v2/get_results/14878&offset=0&limit=250"},"method":"GET","headers":{"content-type":"application/json","accept":"application/json","authorization":"Basic ***Okcz***"}}}}
```

And...

```json
JSON:  {"message":{"error":"Request timed out"},"response":{"statusCode":500,"body":"{\"error\":\"Request timed out\"}","headers":{"date":"Thu, 08 Jul 2021 05:22:33 GMT","content-type":"application/json; charset=utf-8","content-length":"29","connection":"close","server":"Apache","access-control-allow-headers":"authorization, content-type, x-api-ident","access-control-allow-origin":"https://testrail-lite.testrail.io","set-cookie":["tr_session=13afbb8a-33f7-43f5-b6bc-77fd1819c51d; path=/; samesite=none; secure; HttpOnly","notificationbar=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/index"],"vary":"Origin"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"dsvavsp.testrail.io","port":443,"hostname":"dsvavsp.testrail.io","hash":null,"search":"?/api/v2/get_results/1882&offset=0&limit=250","query":"/api/v2/get_results/1882&offset=0&limit=250","pathname":"/index.php","path":"/index.php?/api/v2/get_results/1882&offset=0&limit=250","href":"https://dsvavsp.testrail.io/index.php?/api/v2/get_results/1882&offset=0&limit=250"},"method":"GET","headers":{"content-type":"application/json","accept":"application/json","authorization":"Basic ***Okcz***"}}}}
```

Here's my fix, which I'm testing now:
```javascript
const hitRateLimit = data => data.response.statusCode === 429;
const serverError = data => data.response.statusCode === 500;

// inside getRows()
      while (hitRateLimit(data) || serverError(data)) {
        if (hitRateLimit(data)) {
          const retryAfterSeconds = Number(data.response.headers['retry-after']);
          console.log("Error: 'API Rate Limit Exceeded'");
          console.log(`Waiting ${retryAfterSeconds} seconds...`);
          await new Promise(resolve => setTimeout(resolve, retryAfterSeconds * 1000));
          await callGetFn();
        } else {
          console.log("Error: 'Timeout'");
          await callGetFn();
        }
      }
```

**Comment by holdenhinkle** [comment]
I merged this. I'm 99.99999% sure this is fixed.

I added some statements (for debugging purposes) to log the response data from testrail if the response doesn't include `body`. I'll review the logs every morning. If nothing is logged from these statements in the next few weeks I'll delete them.

**Comment by pjhill** [comment]
Oh, what lovely comments! Thanks for fixing this and explaining the fix.
