### ISSUE TITLE
Perform misc. updates/maintenance on Testing Tools Team Data Dashboard app

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#28718]
Perform misc. updates/maintenance on 'Testing Tools Team Data Dashboard' app.

**Comment by holdenhinkle** [comment]
PRs:
- Delete `node_modules` - https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/pull/56#pullrequestreview-729767318
- `.gitignore` `node_modules` - https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/pull/57
- Remove `@actions/github` package - https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/pull/55
- Refactor `testExecutionId` and `UUID` stuff in `src/mochawesome` - https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/pull/54
- Enable retries for `Post TestRail Data to BigQuery` GHA workflow step - [LINK TO COME]
- Remove useless logging to debug TestRail error and try one more thing (see below) -  - [LINK TO COME]

We're still getting a failure on the `Post TestRail Data to BigQuery` step 1x every week or two. Here's the error:
```
Error: Cannot read property 'statusCode' of undefined
Error TypeError: Cannot read property 'statusCode' of undefined
    at serverError (/home/runner/work/testing-tools-team-dashboard-data/testing-tools-team-dashboard-data/src/testrail/service.js:9:43)
    at Object.getRows (/home/runner/work/testing-tools-team-dashboard-data/testing-tools-team-dashboard-data/src/testrail/service.js:56:17)
    at async Object.tests (/home/runner/work/testing-tools-team-dashboard-data/testing-tools-team-dashboard-data/src/testrail/createTable.js:74:21)
    at async run (/home/runner/work/testing-tools-team-dashboard-data/testing-tools-team-dashboard-data/src/testrail/index.js:14:19)
```

I asked Curt to look this over and he can't figure out why it's happening either.The error occurs when this function is called:
```
const serverError = data => data.response.statusCode === 500;
```

It's called in this conditional:
```
      while (data.response
             && data.response.statusCode
             && hitRateLimit(data)
             || serverError(data))
```

So before I call `serverError()` I verify that `data.response` and `data.response.statusCode` are 'truthy' (not `undefined`). But then `data.response.statusCode` in `serverError()` errors, saying that `data.response` is `undefined`. I don't know why.

I'm going to try one last thing:
```
      while (data.response
             && data.response !== undefined
             && data.response.statusCode
             && data.response.statusCode !== undefined
             && hitRateLimit(data)
             || serverError(data))
```

If that doesn't work, well, I just don't know what haha

Because this bug hasn't been fixed, I enabled retries for the `Post TestRail Data to BigQuery` GHA workflow step. This step usually takes about 41 minutes to run, but occasionally takes just over and hour so I set `timeout` to 90 minutes.

**Comment by pjhill** [comment]
Hooray for more error handling! Thanks for recording all of this into a ticket for posterity. Do we need to expand on the README for the repo in order to describe the error handling in more detail for future maintenance efforts?

**Comment by holdenhinkle** [comment]
I just updated the `README.md` with some notes about retries - https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/pull/61

**Comment by pjhill** [comment]
We have gone a few weeks without errors popping up -- good work!
