### ISSUE TITLE
FixTesting Tools Team Dashboard Data repo workflow error when pushing TestRail data to BigQuery

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#29026]
The TestRail to BigQuery job has been failing the last few days with the following error:

```
PartialFailureError
    at Table._insert (/home/runner/work/testing-tools-team-dashboard-data/testing-tools-team-dashboard-data/node_modules/@google-cloud/bigquery/build/src/table.js:1619:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Table._insertWithRetry (/home/runner/work/testing-tools-team-dashboard-data/testing-tools-team-dashboard-data/node_modules/@google-cloud/bigquery/build/src/table.js:1556:24)
    at async Table._insertAndCreateTable (/home/runner/work/testing-tools-team-dashboard-data/testing-tools-team-dashboard-data/node_modules/@google-cloud/bigquery/build/src/table.js:1518:20) {
  errors: [
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    ... 404 more items
  ],
  response: {
    kind: 'bigquery#tableDataInsertAllResponse',
    insertErrors: [
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      ... 404 more items
    ]
  }
}
```

Fix this.

**Comment by holdenhinkle** [comment]
I fixed it.

I had to update the `ref` column type in the `milestones` table. It was set to `integer` and was `nullable`. It was failing because it should be set to `string`. I'm guessing this column only had `null` values up until recently. I haven't verified this with BQ.

Also, that weird `undefined` bug continues to appear from time to time in `src/testrail/service.js`. I'm trying a few things.

1. I changed:
```js
const serverError = data => data.response.statusCode === 500;
```

to:
```js
const serverError = data => {
  try {
    return data.response.statusCode === 500;
  } catch (error) {
    console.log(error);
    return false;
  }
};
```

Instead of `return data.response.statusCode === 500; ` throwing an error when `data.response` is `undefined`, let's catch the error, log it, and return `false`.

2. I changed:
```js
      while (data.response
             && data.response.statusCode
             && hitRateLimit(data)
             || serverError(data))
```

to:

```js
      while (data
             && data !== undefined
             && data.response
             && data.response !== undefined
             && data.response.statusCode
             && data.response.statusCode !== undefined
             && (
               hitRateLimit(data) || serverError(data)
             )
      )
```

The `while` condition should evaluate to `false` if `data.response` is `undefined` (falsey) but it isn't. So I'm going to try being super explicit.

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/pull/62

This is done.

**Comment by holdenhinkle** [comment]
Woke up to another BigQuery, `milestones` table error:

```
PartialFailureError
    at Table._insert (/home/runner/work/testing-tools-team-dashboard-data/testing-tools-team-dashboard-data/node_modules/@google-cloud/bigquery/build/src/table.js:1619:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Table._insertWithRetry (/home/runner/work/testing-tools-team-dashboard-data/testing-tools-team-dashboard-data/node_modules/@google-cloud/bigquery/build/src/table.js:1556:24)
    at async Table._insertAndCreateTable (/home/runner/work/testing-tools-team-dashboard-data/testing-tools-team-dashboard-data/node_modules/@google-cloud/bigquery/build/src/table.js:1518:20) {
  errors: [
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
    { errors: [Array], row: [Object] },
```

PR to fix `milestone` schema, error: `Field value of due_on cannot be empty.` - https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/pull/63

Removed `, mode: 'REQUIRED'` form schema.

**Comment by pjhill** [comment]
Thanks for resolving this issue
