### ISSUE TITLE
Fix failing tests in vets-api pr 'dependabot/bundler/config-4.1.0'

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#50040]
## Issue Description
Fix failing tests in `vets-api` PR `dependabot/bundler/config-4.1.0`

---
## Tasks
- [x] Fix failing tests

## Acceptance Criteria
- [x] Failing tests pass

**Comment by holdenhinkle** [comment]
The following tests were failing when bumping the `config` gem - https://github.com/department-of-veterans-affairs/vets-api/actions/runs/3566080321/jobs/5992064978

```
Failures:

  1) appointments GET /mobile/v0/appointments pending appointments with feature flag on when pending appointments are included in the query params forms navigation links with query params
     Failure/Error: 
       expect(response.parsed_body['links']).to eq(
         {
           'self' => 'http://www.example.com/mobile/v0/appointments?page[size]=100&page[number]=1&useCache=true&reverseSort=false&include[]=pending&startDate=2020-08-01T10:30:00+00:00&endDate=2021-02-01T10:30:00+00:00',
           'first' => 'http://www.example.com/mobile/v0/appointments?page[size]=100&page[number]=1&useCache=true&reverseSort=false&include[]=pending&startDate=2020-08-01T10:30:00+00:00&endDate=2021-02-01T10:30:00+00:00',
           'prev' => nil,
           'next' => nil,
           'last' => 'http://www.example.com/mobile/v0/appointments?page[size]=100&page[number]=1&useCache=true&reverseSort=false&include[]=pending&startDate=2020-08-01T10:30:00+00:00&endDate=2021-02-01T10:30:00+00:00'
         }
       )

       Expected { "self" => "http://www.example.com/mobile/v0/appointments?page[size]=100&page[number]=1&startDate=2020-08-01T10:30:00+00:00&endDate=2021-02-01T10:30:00+00:00&useCache=true&reverseSort=false&include[]=pending", "first" => "http://www.example.com/mobile/v0/appointments?page[size]=100&page[number]=1&startDate=2020-08-01T10:30:00+00:00&endDate=2021-02-01T10:30:00+00:00&useCache=true&reverseSort=false&include[]=pending", "prev" => nil, "next" => nil, "last" => "http://www.example.com/mobile/v0/appointments?page[size]=100&page[number]=1&startDate=2020-08-01T10:30:00+00:00&endDate=2021-02-01T10:30:00+00:00&useCache=true&reverseSort=false&include[]=pending" }
          to eq { "self" => "http://www.example.com/mobile/v0/appointments?page[size]=100&page[number]=1&useCache=true&reverseSort=false&include[]=pending&startDate=2020-08-01T10:30:00+00:00&endDate=2021-02-01T10:30:00+00:00", "first" => "http://www.example.com/mobile/v0/appointments?page[size]=100&page[number]=1&useCache=true&reverseSort=false&include[]=pending&startDate=2020-08-01T10:30:00+00:00&endDate=2021-02-01T10:30:00+00:00", "prev" => nil, "next" => nil, "last" => "http://www.example.com/mobile/v0/appointments?page[size]=100&page[number]=1&useCache=true&reverseSort=false&include[]=pending&startDate=2020-08-01T10:30:00+00:00&endDate=2021-02-01T10:30:00+00:00" }

       Diff:

       ┌ (Key) ──────────────────────────┐
       │ ‹-› in expected, not in actual  │
       │ ‹+› in actual, not in expected  │
       │ ‹ › in both expected and actual │
       └─────────────────────────────────┘

         {
       -   "self" => "http://www.example.com/mobile/v0/appointments?page[size]=100&page[number]=1&useCache=true&reverseSort=false&include[]=pending&startDate=2020-08-01T10:30:00+00:00&endDate=2021-02-01T10:30:00+00:00",
       +   "self" => "http://www.example.com/mobile/v0/appointments?page[size]=100&page[number]=1&startDate=2020-08-01T10:30:00+00:00&endDate=2021-02-01T10:30:00+00:00&useCache=true&reverseSort=false&include[]=pending",
       -   "first" => "http://www.example.com/mobile/v0/appointments?page[size]=100&page[number]=1&useCache=true&reverseSort=false&include[]=pending&startDate=2020-08-01T10:30:00+00:00&endDate=2021-02-01T10:30:00+00:00",
       +   "first" => "http://www.example.com/mobile/v0/appointments?page[size]=100&page[number]=1&startDate=2020-08-01T10:30:00+00:00&endDate=2021-02-01T10:30:00+00:00&useCache=true&reverseSort=false&include[]=pending",
           "prev" => nil,
           "next" => nil,
       -   "last" => "http://www.example.com/mobile/v0/appointments?page[size]=100&page[number]=1&useCache=true&reverseSort=false&include[]=pending&startDate=2020-08-01T10:30:00+00:00&endDate=2021-02-01T10:30:00+00:00"
       +   "last" => "http://www.example.com/mobile/v0/appointments?page[size]=100&page[number]=1&startDate=2020-08-01T10:30:00+00:00&endDate=2021-02-01T10:30:00+00:00&useCache=true&reverseSort=false&include[]=pending"
         {
           'self' => 'http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=1&useCache=true&reverseSort=false&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00',
           'first' => 'http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=1&useCache=true&reverseSort=false&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00',
           'prev' => nil,
           'next' => 'http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=2&useCache=true&reverseSort=false&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00',
           'last' => 'http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=5&useCache=true&reverseSort=false&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00'
         }
       )

       Expected { "self" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=1&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00&useCache=true&reverseSort=false", "first" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=1&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00&useCache=true&reverseSort=false", "prev" => nil, "next" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=2&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00&useCache=true&reverseSort=false", "last" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=5&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00&useCache=true&reverseSort=false" }
          to eq { "self" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=1&useCache=true&reverseSort=false&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00", "first" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=1&useCache=true&reverseSort=false&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00", "prev" => nil, "next" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=2&useCache=true&reverseSort=false&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00", "last" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=5&useCache=true&reverseSort=false&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00" }

       Diff:

       ┌ (Key) ──────────────────────────┐
       │ ‹-› in expected, not in actual  │
       │ ‹+› in actual, not in expected  │
       │ ‹ › in both expected and actual │
       └─────────────────────────────────┘

         {
       -   "self" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=1&useCache=true&reverseSort=false&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00",
       +   "self" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=1&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00&useCache=true&reverseSort=false",
       -   "first" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=1&useCache=true&reverseSort=false&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00",
       +   "first" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=1&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00&useCache=true&reverseSort=false",
           "prev" => nil,
       -   "next" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=2&useCache=true&reverseSort=false&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00",
       +   "next" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=2&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00&useCache=true&reverseSort=false",
       -   "last" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=5&useCache=true&reverseSort=false&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00"
       +   "last" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=5&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00&useCache=true&reverseSort=false"
         }
     # /usr/local/bundle/gems/super_diff-0.9.0/lib/super_diff/rspec/monkey_patches.rb:43:in `handle_failure'
     # ./modules/mobile/spec/request/appointments_list_request_spec.rb:254:in `block (6 levels) in <top (required)>'
     # /usr/local/bundle/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
     # /usr/local/bundle/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
     # /usr/local/bundle/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
     # /usr/local/bundle/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
     # /usr/local/bundle/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # /usr/local/bundle/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'

  5) appointments GET /mobile/v0/appointments with valid params when there are cached appointments pagination when the last page is requested has the correct links with no next
     Failure/Error: 
       expect(response.parsed_body['links']).to eq(
         {
           'self' => 'http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=5&useCache=true&reverseSort=false&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00',
           'first' => 'http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=1&useCache=true&reverseSort=false&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00',
           'prev' => 'http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=4&useCache=true&reverseSort=false&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00',
           'next' => nil,
           'last' => 'http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=5&useCache=true&reverseSort=false&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00'
         }
       )

       Expected { "self" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=5&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00&useCache=true&reverseSort=false", "first" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=1&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00&useCache=true&reverseSort=false", "prev" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=4&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00&useCache=true&reverseSort=false", "next" => nil, "last" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=5&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00&useCache=true&reverseSort=false" }
          to eq { "self" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=5&useCache=true&reverseSort=false&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00", "first" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=1&useCache=true&reverseSort=false&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00", "prev" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=4&useCache=true&reverseSort=false&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00", "next" => nil, "last" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=5&useCache=true&reverseSort=false&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00" }

       Diff:

       ┌ (Key) ──────────────────────────┐
       │ ‹-› in expected, not in actual  │
       │ ‹+› in actual, not in expected  │
       │ ‹ › in both expected and actual │
       └─────────────────────────────────┘

         {
       -   "self" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=5&useCache=true&reverseSort=false&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00",
       +   "self" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=5&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00&useCache=true&reverseSort=false",
       -   "first" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=1&useCache=true&reverseSort=false&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00",
       +   "first" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=1&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00&useCache=true&reverseSort=false",
       -   "prev" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=4&useCache=true&reverseSort=false&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00",
       +   "prev" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=4&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00&useCache=true&reverseSort=false",
           "next" => nil,
       -   "last" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=5&useCache=true&reverseSort=false&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00"
       +   "last" => "http://www.example.com/mobile/v0/appointments?page[size]=5&page[number]=5&startDate=2019-01-01T00:00:00+00:00&endDate=2021-02-01T10:30:00+00:00&useCache=true&reverseSort=false"
         }
     # /usr/local/bundle/gems/super_diff-0.9.0/lib/super_diff/rspec/monkey_patches.rb:43:in `handle_failure'
     # ./modules/mobile/spec/request/appointments_list_request_spec.rb:320:in `block (6 levels) in <top (required)>'
     # /usr/local/bundle/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
     # /usr/local/bundle/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
     # /usr/local/bundle/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
     # /usr/local/bundle/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
     # /usr/local/bundle/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # /usr/local/bundle/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'

Finished in 1 minute 31.4 seconds (files took 29.95 seconds to load)
879 examples, 5 failures

Failed examples:

rspec ./modules/mobile/spec/request/appointments_list_request_spec.rb:1315 # appointments GET /mobile/v0/appointments pending appointments with feature flag on when pending appointments are included in the query params forms navigation links with query params
rspec ./modules/mobile/spec/request/appointments_list_request_spec.rb:354 # appointments GET /mobile/v0/appointments with valid params when there are cached appointments pagination when an out of bounds page is requested has the correct links with no next
rspec ./modules/mobile/spec/request/appointments_list_request_spec.rb:286 # appointments GET /mobile/v0/appointments with valid params when there are cached appointments pagination when a middle page is requested has the correct links both prev and next
rspec ./modules/mobile/spec/request/appointments_list_request_spec.rb:253 # appointments GET /mobile/v0/appointments with valid params when there are cached appointments pagination when the first page is requested has the correct links with no prev
rspec ./modules/mobile/spec/request/appointments_list_request_spec.rb:319 # appointments GET /mobile/v0/appointments with valid params when there are cached appointments pagination when the last page is requested has the correct links with no next
```

The order of the query params changed in the response. I updated the expected response to match actual.

* None of the query param values changed and no additional query params were added.

**Comment by holdenhinkle** [comment]
Merged - https://github.com/department-of-veterans-affairs/vets-api/pull/11166
