### ISSUE TITLE
Ruby 3 Spec Failure: AttachmentRequestSpec

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#54266]
When running our Vets API test suite using Ruby 3.0.5, various examples fail.

One such example is within the AttachmentRequestSpec:
```
rspec ./spec/requests/v0/form1010cg/attachments_request_spec.rb:49
rspec ./spec/requests/v0/form1010cg/attachments_request_spec.rb:49
```

It fails with a 500 (expecting 200).

Logs:

```
  1) Form 10-10CG Attachments POST /v0/form1010cg/attachments with JPG accepts a file upload
     Failure/Error: expect(response).to have_http_status(:ok)
       expected the response to have status code :ok (200) but it was :internal_server_error (500)
     # ./.bundle/bundle/ruby/3.0.0/gems/super_diff-0.9.0/lib/super_diff/rspec/monkey_patches.rb:45:in `handle_failure'
     # ./spec/requests/v0/form1010cg/attachments_request_spec.rb:53:in `block (5 levels) in <top (required)>'
     # ./.bundle/bundle/ruby/3.0.0/gems/vcr-6.1.0/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
     # ./.bundle/bundle/ruby/3.0.0/gems/vcr-6.1.0/lib/vcr.rb:194:in `use_cassette'
     # ./spec/requests/v0/form1010cg/attachments_request_spec.rb:50:in `block (4 levels) in <top (required)>'
```

## AC

- [ ] AttachmentRequestSpec passes for Ruby 3.0.5

**Comment by oseasmoran73** [comment]
Looks like it has been resolved. Moving to review state so @ericboehs can verify
