### ISSUE TITLE
Ruby 3 Spec Failure: SessionsController

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#54271]
When running our Vets API test suite using Ruby 3.0.5, various examples fail.

One such example is:
```
rspec ./spec/controllers/v1/sessions_controller_spec.rb:421
rspec ./spec/controllers/v1/sessions_controller_spec.rb:427
rspec ./spec/controllers/v1/sessions_controller_spec.rb:447
rspec ./spec/controllers/v1/sessions_controller_spec.rb:393
rspec ./spec/controllers/v1/sessions_controller_spec.rb:658
rspec ./spec/controllers/v1/sessions_controller_spec.rb:1008
rspec ./spec/controllers/v1/sessions_controller_spec.rb:1035
rspec ./spec/controllers/v1/sessions_controller_spec.rb:1049
rspec ./spec/controllers/v1/sessions_controller_spec.rb:1076
```

The first one fails trying to redirect with error code 007 instead of 102.

Logs:

```
1) V1::SessionsController when not logged in POST saml_callback for a user with semantically invalid SAML attributes redirects to an auth failure page
   Failure/Error: expect(post(:saml_callback)).to redirect_to(expected_redirect)

     Expected response to be a redirect to <http://127.0.0.1:3001/auth/login/callback?auth=fail&code=102&request_id=c570c262-b091-4a25-87f5-abe437afc47f> but was a redirect to <http://127.0.0.1:3001/auth/login/callback?auth=fail&code=007&request_id=c570c262-b091-4a25-87f5-abe437afc47f>.
     Expected "http://127.0.0.1:3001/auth/login/callback?auth=fail&code=102&request_id=c570c262-b091-4a25-87f5-abe437afc47f" to be === "http://127.0.0.1:3001/auth/login/callback?auth=fail&code=007&request_id=c570c262-b091-4a25-87f5-abe437afc47f".
   # ./.bundle/bundle/ruby/3.0.0/gems/super_diff-0.9.0/lib/super_diff/rspec/monkey_patches.rb:45:in `handle_failure'
   # ./spec/controllers/v1/sessions_controller_spec.rb:423:in `block (5 levels) in <top (required)>'
```

## AC

- [ ] SessionsController spec passes for Ruby 3.0.5

**Comment by oseasmoran73** [comment]
[Slack](https://dsva.slack.com/archives/C045C97V7N1/p1678143025282869) where SSOE fix resolves this ticket. Moving to review column

**Comment by oseasmoran73** [comment]
@ericboehs Closing ticket as SSOE PR has been merged
