### ISSUE TITLE
Ruby 3 Spec Failure: CaregiversAssistanceClaimsController

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#54272]
When running our Vets API test suite using Ruby 3.0.5, various examples fail.

One such example is:
```
rspec ./spec/controllers/v0/caregivers_assistance_claims_controller_spec.rb:25
rspec ./spec/controllers/v0/caregivers_assistance_claims_controller_spec.rb:49
```

It fails with a 500 (expecting 400).

Logs:

```
1) V0::CaregiversAssistanceClaimsController#download_pdf behaves like 10-10CG request with missing param: caregivers_assistance_claim requires "caregivers_assistance_claim" param
   Failure/Error: expect(response).to have_http_status(:bad_request)
     expected the response to have status code :bad_request (400) but it was :internal_server_error (500)
   Shared Example Group: "10-10CG request with missing param: caregivers_assistance_claim" called from ./spec/controllers/v0/caregivers_assistance_claims_controller_spec.rb:188
   # ./.bundle/bundle/ruby/3.0.0/gems/super_diff-0.9.0/lib/super_diff/rspec/monkey_patches.rb:45:in `handle_failure'
   # ./spec/controllers/v0/caregivers_assistance_claims_controller_spec.rb:28:in `block (3 levels) in <top (required)>'
```

## AC

- [ ] CaregiversAssistanceClaimsController spec passes for Ruby 3.0.5

**Comment by oseasmoran73** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/11929

Moving to review state for @ericboehs to verify
