### ISSUE TITLE
Research cause of Yarn install issue

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#60685]

**Comment by pjhill** [comment]
Error being spit out into the logs during `yarn install` :
```error /app/website/slow/pe_slow_content_build/vets-website/src/platform/testing/node_modules/puppeteer: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /app/website/slow/pe_slow_content_build/vets-website/src/platform/testing/node_modules/puppeteer
Output:
ERROR: Failed to set up Chromium r756035! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/app/website/slow/pe_slow_content_build/vets-website/src/platform/testing/node_modules/puppeteer/lib/helper.js:94:19)
    at fetchBinary (/app/website/slow/pe_slow_content_build/vets-website/src/platform/testing/node_modules/puppeteer/install.js:148:8)
    at download (/app/website/slow/pe_slow_content_build/vets-website/src/platform/testing/node_modules/puppeteer/install.js:54:9) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN'
}```

**Comment by pjhill** [comment]
In order to more quickly wipe out the previous attempt at a build, I used the below code to move the build out of the way and then remove it async --
```
#!/bin/sh
echo "Navigate into /app/website/slow"
cd website/slow
echo "Generating timestamp"
TIMESTAMP=$(date +%s)
echo "Timestamp value: " $TIMESTAMP
echo "Moving: " $SOURCE_REF " to " $SOURCE_REF"-"$TIMESTAMP
mv -vf $SOURCE_REF $SOURCE_REF"-"$TIMESTAMP
echo "Removing previous build in background"
rm -rf $SOURCE_REF"-"$TIMESTAMP &
echo "Creating directory: " $SOURCE_REF
mkdir $SOURCE_REF
echo "Navigate into: " $SOURCE_REF
cd $SOURCE_REF
```

**Comment by pjhill** [comment]
I just realized when I'm manually executing the steps in the terminal through ArgoCD, I am using `yarn install` and not `yarn install --production=false`.

Last experiment of the day, I'm going to try this --

```
echo "set yarn to allow self-signed cert for install"
yarn config set "strict-ssl" false -g
echo "set puppeteer to not download"
PUPPETEER_SKIP_DOWNLOAD='true'

# Build and watch vets-website
echo "Install, build, and watch vets-website"
cd vets-website
echo "Installing"
yarn install #--production=false
echo "Waiting for yarn install to finish before proceeding"
wait
```

**Comment by pjhill** [comment]
Borrowed the CA cert loading script from `vets-api` --

```
#!/bin/sh

(
    cd /usr/local/share/ca-certificates/

    curl -LO https://cacerts.digicert.com/DigiCertTLSRSASHA2562020CA1-1.crt.pem

    wget \
        --level=1 \
        --quiet \
        --recursive \
        --no-parent \
        --no-host-directories \
        --no-directories \
        --accept="VA*.cer" \
        http://aia.pki.va.gov/PKI/AIA/VA/

    for cert in *.{cer,pem}
    do
        if file "${cert}" | grep 'PEM'
        then
            cp "${cert}" "${cert}.crt"
        else
            openssl x509 -in "${cert}" -inform der -outform pem -out "${cert}.crt"
        fi
        rm "${cert}"
    done

    update-ca-certificates --fresh

    # Display VA Internal certificates that are now trusted
    awk -v cmd='openssl x509 -noout -subject' '/BEGIN/{close(cmd)};{print | cmd}' < /etc/ssl/certs/ca-certificates.crt \
    | grep -iE '(VA-Internal|DigiCert)'
)
```

Copying the script into place and loading it at docker build time --
```
# Download VA Certs
COPY ./src/platform/utilities/preview-environment/import-va-certs.sh .
RUN ./import-va-certs.sh
```

**Comment by pjhill** [comment]
Running the script after the container starts reveals the following errors --
```
root@ri-vets-website-rework-pe-frontend-7b66c87db5-6hp98:/app# ls
import-va-certs.sh  start.sh  website
root@ri-vets-website-rework-pe-frontend-7b66c87db5-6hp98:/app# ./import-va-certs.sh 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
./import-va-certs.sh: 20: ./import-va-certs.sh: file: not found
Can't open *.{cer,pem} for reading, No such file or directory
139962389935232:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:69:fopen('*.{cer,pem}','rb')
139962389935232:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:76:
unable to load certificate
rm: cannot remove '*.{cer,pem}': No such file or directory
Clearing symlinks in /etc/ssl/certs...
done.
Updating certificates in /etc/ssl/certs...
137 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
subject=C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Assured ID Root CA
subject=C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Assured ID Root G2
subject=C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Assured ID Root G3
subject=C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
subject=C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root G2
subject=C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root G3
subject=C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert High Assurance EV Root CA
subject=C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Trusted Root G4
root@ri-vets-website-rework-pe-frontend-7b66c87db5-6hp98:/app# 
```

**Comment by pjhill** [comment]
Questions we would like answered in order to make progress:
1. Why did this `yarn` issue pop up in the first place?
2. Are the certificates really being successfully loaded by the script borrowed from `vets-api`?

**Comment by rmessina1010** [comment]
Explored:
1.  The script/install script crashes in a way that terminates the docker container/pod;  making it difficult to diagnose the  internal process that could be leading to said failure.
(To solve this we  temporarily  added  a `sleep` command  to the docker file,  preventing the container from  terminating;  giving us a few minutes to peek into the terminal and see what was going on)
2. I does seem that the current  culprit is are the certs; it may not be the only thing, but  it's best to analyze one thing at a time.
(My thought was is that  the certificates  may be getting accidentally deleted during the clearing of the  previous volume. Peter and I did discover that this loop in `import-va-certs.sh` is not working properly and may be the  root  of the issue.
```
    for cert in *.{cer,pem}
    do
        if file "${cert}" | grep 'PEM'
        then
            cp "${cert}" "${cert}.crt"
        else
            openssl x509 -in "${cert}" -inform der -outform pem -out "${cert}.crt"
        fi
        rm "${cert}"
    done
```

**Comment by rmessina1010** [comment]
I added a `echo {$cert}` statements to the steps inside the `for` loop in order to pinpoint the reason why the output was missing some certificates.   My theory being that it could be one of 3 scenarios:
1. The loop is NOT reading all the certs files from the source ( we could then dig into this further to see if it's the curl  not bring in the file or something else)
2. If the  statements within the `for` loop are failing  to copy existing .crt / create the converted .crts
3. If the loop IS working, but the rm statement is inadvertently deleting needed .crts
[Note: it is possible   for multiple causes to exist ...example:#2 & #3.]
My commit is meant to create a easier way to diagnose what is happening when `import-va-cert.sh` runs.

As a side note,  I am expecting that in some cases `${cert}`  may already contain the suffix '.crt', and as such the newly created files get deleted in `rm "${cert}"`

**Comment by rmessina1010** [comment]
With the help of Cyril,  I attempted to run the above commit or ArgoCD.

1) I could not observe the expected echoed statments?
2) I also noticed that `/usr/local/share/ca-certificates/`  only contained  `mozila`; which is odd because more certs were present when Peter Hill and I started on this the previous Friday.
3) Cyril also added RUN `chmod +x import-va-certs.sh`, as he thinks  the script may not be running at all  due to lack of permissions

**Comment by JoeTice** [comment]
**Sprint 30 Update** - IN PROGRESS. This task is our primary focus and was worked on by Peter and Ray M this sprint, progress was made but the issue is not yet resolved. Expect work on this to be completed in Sprint 31.

**Comment by pjhill** [comment]
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/45410c3a-cf1e-4f6c-98f9-8f175e0d7927)

**Comment by CBonade** [comment]
We've managed to move this forward, however the process seems to potentially die without explanation. We are working on verbose logging to try and get more information, however, it's very slow-going.
