### ISSUE TITLE
eFSR Sentry Error Bugfix

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-team#61354]
This ticket addresses a the `undefined(reading 'includes') bug that is preventing submissions when expense.name is undefined which is blocking form submission for some users.

![Screenshot 2023-07-03 at 3.12.47 PM.png](https://images.zenhubusercontent.com/63bdb210656b9fedf3821d8d/671a11c7-2e12-4d72-a186-2e429b463f60)

this is the error message
```
Uncaught TypeError: Cannot read properties of undefined (reading 'includes')
    at request-debt-help-form-5655.entry.js:63665:25
    at Array.find (<anonymous>)
    at Object.transform [as transformForSubmit] (request-debt-help-form-5655.entry.js:63664:99)
    at Object.submitForm [as submit] (request-debt-help-form-5655.entry.js:55079:57)
    at request-debt-help-form-5655.entry.js:70994:28
    at request-debt-help-form-5655.entry.js:208416:18
    at boundActionCreators.<computed> [as submitForm] (request-debt-help-form-5655.entry.js:189493:16)
    at request-debt-help-form-5655.entry.js:76869:19
    at HTMLUnknownElement.callCallback (request-debt-help-form-5655.entry.js:161435:14)
    at Object.invokeGuardedCallbackDev (request-debt-help-form-5655.entry.js:161484:16)
```

The error is on line 154 in the transform.js

**Comment by amponce** [comment]
trigger errror with scrubbed prod data

```
{
  "additional_data": {
    "additional_comments": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "bankruptcy": {}
  },
  "expenses": {
    "rent_or_mortgage": "3000",
    "food": "00.00"
  },
  "assets": {
    "automobiles": [
      {
        "make": "Ford",
        "model": "F150",
        "year": "2020",
        "resale_value": "34000"
      }
    ],
    "cash_in_bank": "0.00",
    "cash_on_hand": "00.00",
    "us_savings_bonds": "00.00",
    "stocks_and_other_bonds": "00.00"
  },
  "view:components": {
    "view:vehicle_info": {},
    "view:asset_info": {},
    "view:marital_status": {},
    "view:veteran_info": {},
    "view:va_benefits_on_file": {},
    "view:real_estate_additional_info": {},
    "view:rec_vehicle_info": {}
  },
  "questions": {
    "has_vehicle": true,
    "has_been_adjudicated_bankrupt": false,
    "has_other_expenses": false,
    "has_repayments": true,
    "has_utilities": false,
    "has_other_assets": false,
    "has_recreational_vehicle": false,
    "has_real_estate": false,
    "has_dependents": false,
    "is_married": false,
    "has_additional_income": false,
    "has_social_security": false,
    "vet_is_employed": true
  },
  "other_expenses": [
    {}
  ],
  "installment_contracts": [
    {
      "purpose": "Car payment/lease",
      "creditor_name": "Capital one",
      "original_amount": "45000",
      "unpaid_balance": "41000",
      "amount_due_monthly": "800.00",
      "date_started": "2021-08-XX",
      "amount_past_due": "41000"
    }
  ],
  "personal_data": {
    "employment_history": {
      "veteran": {
        "employment_records": [
          {
            "type": "Part time",
            "from": "2019-08-XX",
            "to": "2023-01-XX",
            "employer_name": "VA"
          }
        ]
      },
      "spouse": {}
    },
    "address": {
      "lives_outside_us": true,
      "lives_on_military_base_info": {},
      "country": "USA",
      "street": "123 Main St",
      "city": "FPO",
      "state": "AA",
      "postal_code": "12345"
    },
    "telephone_number": "1234567890",
    "email_address": "PROD.USER@GMAIL.COM",
    "veteran_full_name": {
      "first": "PROD",
      "last": "USER",
      "middle": "MIDDLE"
    },
    "date_of_birth": "1988-07-03",
    "veteran_contact_information": {
      "address": {},
      "mobile_phone": {}
    },
    "spouse_full_name": {}
  },
  "personal_identification": {
    "ssn": "1234",
    "file_number": "1234"
  },
  "selected_debts": [
    {
      "file_number": "123456789",
      "payee_number": "00",
      "person_entitled": "PRODUS",
      "deduction_code": "71",
      "benefit_type": "CH33 Books, Supplies/MISC EDU",
      "diary_code": "117",
      "diary_code_description": "Second Demand Letter",
      "amount_overpaid": 186.67,
      "amount_withheld": 0,
      "original_ar": 186.67,
      "current_ar": 186.67,
      "debt_history": [
        {
          "date": "06/14/2023",
          "letter_code": "100",
          "description": "First Demand Letter - Inactive Benefits - Due Process"
        }
      ],
      "id": 0,
      "debt_type": "DEBT"
    },
    {
      "file_number": "123456789",
      "payee_number": "00",
      "person_entitled": "PRODUS",
      "deduction_code": "72",
      "benefit_type": "CH33 Housing EDU",
      "diary_code": "117",
      "diary_code_description": "Second Demand Letter",
      "amount_overpaid": 1715.52,
      "amount_withheld": 0,
      "original_ar": 1715.52,
      "current_ar": 1715.52,
      "debt_history": [
        {
          "date": "06/14/2023",
          "letter_code": "100",
          "description": "First Demand Letter - Inactive Benefits - Due Process"
        }
      ],
      "id": 1,
      "debt_type": "DEBT"
    }
  ],
  "selected_debts_and_copays": [
    {
      "resolution_waiver_check": true,
      "resolution_option": "waiver",
      "file_number": "123456789",
      "payee_number": "00",
      "person_entitled": "PRODUS",
      "deduction_code": "71",
      "benefit_type": "CH33 Books, Supplies/MISC EDU",
      "diary_code": "117",
      "diary_code_description": "Second Demand Letter",
      "amount_overpaid": 266.67,
      "amount_withheld": 0,
      "original_ar": 266.67,
      "current_ar": 266.67,
      "debt_history": [
        {
          "date": "06/14/2023",
          "letter_code": "100",
          "description": "First Demand Letter - Inactive Benefits - Due Process"
        }
      ],
      "id": 0,
      "debt_type": "DEBT",
      "resolution_comment": ""
    },
    {
      "resolution_waiver_check": true,
      "resolution_option": "waiver",
      "file_number": "123456789",
      "payee_number": "00",
      "person_entitled": "PRODUS",
      "deduction_code": "72",
      "benefit_type": "CH33 Housing EDU",
      "diary_code": "117",
      "diary_code_description": "Second Demand Letter",
      "amount_overpaid": 1715.52,
      "amount_withheld": 0,
      "original_ar": 1715.52,
      "current_ar": 1715.52,
      "debt_history": [
        {
          "date": "06/14/2023",
          "letter_code": "100",
          "description": "First Demand Letter - Inactive Benefits - Due Process"
        }
      ],
      "id": 1,
      "debt_type": "DEBT",
      "resolution_comment": ""
    }
  ],
  "debt": {
    "current_ar": 0,
    "debt_history": [
      {
        "date": ""
      }
    ],
    "deduction_code": "",
    "original_ar": 0
  },
  "curr_employment": [],
  "social_security": {
    "spouse": {}
  },
  "additional_income": {
    "spouse": {}
  },
  "benefits": {
    "spouse_benefits": {}
  },
  "financial_overview": {},
  "available_options": {},
  "view:combined_financial_status_report": true,
  "view:enhanced_financial_status_report": false,
  "income": [
    {
      "veteran_or_spouse": "VETERAN",
      "compensation_and_pension": "1062.21",
      "education": "152"
    }
  ],
  "agreed": true
}```
