### ISSUE TITLE
Identity Dashboard (FE) - Fix failing test - `reason: response3.headers.all is not a function`

### ISSUE THREAD

**Issue by acald-creator** [department-of-veterans-affairs/va.gov-team#66194]
In the recent merged PRs, there is a failing test at this link https://github.com/department-of-veterans-affairs/identity-dashboard-fe/actions/runs/6279036438/job/17053994628

Description of error:

```bash
PASS __testing__/lib/auth/crypto.test.js
FAIL __testing__/lib/auth/index.test.js
  ● authentication › requestToken › make a POST request to the proper `/token` URL

    FetchError: request to https://localhost:3000/v0/sign_in/token/?type=logingov&grant_type=authorization_code&client_id=identity_dashboard&code=real_code_here&code_verifier=dE9H-MFrv492oK6Of-16QXaxtryQhkzW6YWW6hWpoQpXiMjJT6CiVMg2q3KVrT6m failed, reason: response3.headers.all is not a function

      at NodeClientRequest.<anonymous> (node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib/index.js:1501:11)
      at NodeClientRequest.Object.<anonymous>.NodeClientRequest.emit (node_modules/.pnpm/@mswjs+interceptors@0.17.10/node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/NodeClientRequest.ts:299:22)
      at node_modules/.pnpm/@mswjs+interceptors@0.17.10/node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/NodeClientRequest.ts:153:14
```

**Comment by acald-creator** [comment]
This was completed via PR: https://github.com/department-of-veterans-affairs/identity-dashboard-fe/pull/81
