### ISSUE TITLE
Get vets-api specs running successfully on CircleCI

### ISSUE THREAD

**Issue by johnpaulashenfelter** [department-of-veterans-affairs/va.gov-team#7078]
Setup CircleCI, based on the branch from @bkjohnson. Add and update the appropriate 3rd party libraries and versions

- [x] Ruby 2.6.5
- [x] Postgresql 11.5 + Postgis
- [x] Redis 3.x

Configure the basic test steps for

- [x] Creating a database
- [x] Loading the schema
- [x] Running the tests

Finish everything up by

- [ ] Using `dockerize` to wait for redis and postgresql to boot to avoid silly failures when db/etc is not ready

**Comment by johnpaulashenfelter** [comment]
Successful basic setup here: https://app.circleci.com/pipelines/github/bkjohnson/vets-api/14/workflows/1618283b-a395-45d0-b2f9-7775ba9c215b/jobs/19

But there's a fair bit of configuration to fight with database username/password/etc connectivity.

**Comment by johnpaulashenfelter** [comment]
Added a step to use `dockerize` to make sure redis and postgres in particular are up and running before running database steps. Lots of docs on this.

**Comment by johnpaulashenfelter** [comment]
Blocked pretty hard by some weird errors starting with

```
An error occurred while loading ./spec/workers/gi_bill_feedback_submission_job_spec.rb.
Failure/Error: require File.expand_path('../config/environment', __dir__)

RuntimeError:
  No such middleware to insert before: Rails::Rack::Logger
# ./vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/stack.rb:108:in `assert_index'
# ./vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/stack.rb:87:in `swap'
# ./vendor/bundle/ruby/2.6.0/gems/rails_semantic_logger-4.4.0/lib/rails_semantic_logger/engine.rb:38:in `block in <class:Engine>'
# ./vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `instance_exec'
# ./vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `run'
# ./vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
# ./vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:50:in `each'
# ./vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:50:in `tsort_each_child'
# ./vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:60:in `run_initializers'
# ./vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/application.rb:361:in `initialize!'
# ./config/environment.rb:7:in `<top (required)>'
# ./vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
# ./vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
# ./vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
# ./vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
# ./spec/rails_helper.rb:6:in `<top (required)>'
# ./vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
# ./vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
# ./vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
# ./vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
# ./spec/workers/gi_bill_feedback_submission_job_spec.rb:3:in `<top (required)>'
# ./vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `load'
# ./vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `block in load'
# ./vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
# ./vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `load'```

getting dozens of those.

Dug in a little w/ semantic logging, added the config from `environments/development.rb` which is

```
  config.rails_semantic_logger.semantic   = false
  config.rails_semantic_logger.started    = true
  config.rails_semantic_logger.processing = true
  config.rails_semantic_logger.rendered   = true
end```

but that led to 

An error occurred while loading ./spec/controllers/v1/sessions_controller_spec.rb.
Failure/Error: require File.expand_path("../../config/environment", __FILE__)

FrozenError:
  can't modify frozen Array
# ./vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/stack.rb:76:in `insert'
# ./vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/stack.rb:76:in `insert'
# ./vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/stack.rb:83:in `insert_after'
# ./vendor/bundle/ruby/2.6.0/gems/request_store-1.5.0/lib/request_store/railtie.rb:5:in `block in <class:Railtie>'
# ./vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `instance_exec'
# ./vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `run'
# ./vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
# ./vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:60:in `run_initializers'
# ./vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/application.rb:361:in `initialize!'
# ./config/environment.rb:7:in `<top (required)>'
# ./vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
# ./vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
# ./vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
# ./vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
# ./spec/rails_helper.rb:6:in `<top (required)>'
# ./vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
# ./vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
# ./vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
# ./vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
# ./spec/controllers/v1/sessions_controller_spec.rb:3:in `<top (required)>'
# ./vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `load'
# ./vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `block in load'
# ./vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
# ./vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `load'


Also tried with the `RAILS_ENABLE_TEST_LOG` env var toggled to true, but no difference.

Something is really weird here. Might need to dig through dockerfile to see what other things get set.

**Comment by johnpaulashenfelter** [comment]
Spent a bunch of hours ssh'd into a circleci server trying some configuration, some gems. Also dug through the setup process (poppler, pdftk, etc) like we'd do for a local install without a lot of success. SOMEthing is different in the startup order but no luck finding out what. 

* Tried deleting all the docker files just in case -- same result (which is good)
* Dug around in different versions of the logger 

$ cat Gemfile.lock | grep semantic
    rails_semantic_logger (4.4.0)
      semantic_logger (~> 4.4)
    semantic_logger (4.5.0)
  rails_semantic_logger (~> 4.4)

- from master

updated to latest and no real change.

**Comment by johnpaulashenfelter** [comment]
Turns out to be eager loading when the CI env var is set. Now I'm down to some real failures, likely Iconv version-related.

Failures:

  1) EducationForm::Forms::VA1990 1990 kitchen_sink_active_duty spool test generates the spool file correctly
     Failure/Error: transliterated = Iconv.iconv('ascii//translit', 'utf-8', wrapped).first
     
     Iconv::IllegalSequence:
       "’s in JSON docum"...
     # ./app/workers/education_form/forms/base.rb:74:in `iconv'
     # ./app/workers/education_form/forms/base.rb:74:in `format'
     # ./app/workers/education_form/forms/base.rb:64:in `initialize'
     # ./spec/support/spool_helpers.rb:11:in `new'
     # ./spec/support/spool_helpers.rb:11:in `block (2 levels) in test_spool_file'
     # ./spec/support/spool_helpers.rb:32:in `block (2 levels) in test_spool_file'
     # ./spec/spec_helper.rb:133:in `block (2 levels) in <top (required)>'

  2) EducationForm::Forms::VA1990 1990 kitchen_sink spool test generates the spool file correctly
     Failure/Error: transliterated = Iconv.iconv('ascii//translit', 'utf-8', wrapped).first
     
     Iconv::IllegalSequence:
       "’s in JSON docum"...
     # ./app/workers/education_form/forms/base.rb:74:in `iconv'
     # ./app/workers/education_form/forms/base.rb:74:in `format'
     # ./app/workers/education_form/forms/base.rb:64:in `initialize'
     # ./spec/support/spool_helpers.rb:11:in `new'
     # ./spec/support/spool_helpers.rb:11:in `block (2 levels) in test_spool_file'
     # ./spec/support/spool_helpers.rb:32:in `block (2 levels) in test_spool_file'
     # ./spec/spec_helper.rb:133:in `block (2 levels) in <top (required)>'

  3) EducationForm::Forms::VA1990 1990 kitchen_sink_edu_prog spool test generates the spool file correctly
     Failure/Error: transliterated = Iconv.iconv('ascii//translit', 'utf-8', wrapped).first
     
     Iconv::IllegalSequence:
       "’s in JSON docum"...
     # ./app/workers/education_form/forms/base.rb:74:in `iconv'
     # ./app/workers/education_form/forms/base.rb:74:in `format'
     # ./app/workers/education_form/forms/base.rb:64:in `initialize'
     # ./spec/support/spool_helpers.rb:11:in `new'
     # ./spec/support/spool_helpers.rb:11:in `block (2 levels) in test_spool_file'
     # ./spec/support/spool_helpers.rb:32:in `block (2 levels) in test_spool_file'
     # ./spec/spec_helper.rb:133:in `block (2 levels) in <top (required)>'

  4) vaos appointment request messages POST message loa3 user with access and valid message posts a message
     Failure/Error: expect(response).to have_http_status(:success)
       expected the response to have a success status code (2xx) but it was 500
     # ./modules/vaos/spec/request/messages_request_spec.rb:87:in `block (6 levels) in <top (required)>'
     # ./modules/vaos/spec/request/messages_request_spec.rb:84:in `block (5 levels) in <top (required)>'

  5) vaos appointment request messages GET messages loa3 user has access and returns messages
     Failure/Error: expect(response).to have_http_status(:success)
       expected the response to have a success status code (2xx) but it was 500
     # ./modules/vaos/spec/request/messages_request_spec.rb:44:in `block (5 levels) in <top (required)>'
     # ./modules/vaos/spec/request/messages_request_spec.rb:41:in `block (4 levels) in <top (required)>'

  6) EducationForm::Forms::VA1990e 1990e kitchen_sink spool test generates the spool file correctly
     Failure/Error: transliterated = Iconv.iconv('ascii//translit', 'utf-8', wrapped).first
     
     Iconv::IllegalSequence:
       "’s in JSON docum"...
     # ./app/workers/education_form/forms/base.rb:74:in `iconv'
     # ./app/workers/education_form/forms/base.rb:74:in `format'
     # ./app/workers/education_form/forms/base.rb:64:in `initialize'
     # ./spec/support/spool_helpers.rb:11:in `new'
     # ./spec/support/spool_helpers.rb:11:in `block (2 levels) in test_spool_file'
     # ./spec/support/spool_helpers.rb:32:in `block (2 levels) in test_spool_file'
     # ./spec/spec_helper.rb:133:in `block (2 levels) in <top (required)>'

  7) EducationForm::Forms::VA5490 5490 simple_chapter_33_child spool test generates the spool file correctly
     Failure/Error: transliterated = Iconv.iconv('ascii//translit', 'utf-8', wrapped).first
     
     Iconv::IllegalSequence:
       "’M CHOOSING TO R"...
     # ./app/workers/education_form/forms/base.rb:74:in `iconv'
     # ./app/workers/education_form/forms/base.rb:74:in `format'
     # ./app/workers/education_form/forms/base.rb:64:in `initialize'
     # ./spec/support/spool_helpers.rb:11:in `new'
     # ./spec/support/spool_helpers.rb:11:in `block (2 levels) in test_spool_file'
     # ./spec/support/spool_helpers.rb:32:in `block (2 levels) in test_spool_file'
     # ./spec/spec_helper.rb:133:in `block (2 levels) in <top (required)>'

  8) EducationForm::Forms::VA5490 5490 kitchen_sink_chapter_35_child spool test generates the spool file correctly
     Failure/Error: transliterated = Iconv.iconv('ascii//translit', 'utf-8', wrapped).first
     
     Iconv::IllegalSequence:
       "’M CHOOSING TO R"...
     # ./app/workers/education_form/forms/base.rb:74:in `iconv'
     # ./app/workers/education_form/forms/base.rb:74:in `format'
     # ./app/workers/education_form/forms/base.rb:64:in `initialize'
     # ./spec/support/spool_helpers.rb:11:in `new'
     # ./spec/support/spool_helpers.rb:11:in `block (2 levels) in test_spool_file'
     # ./spec/support/spool_helpers.rb:32:in `block (2 levels) in test_spool_file'
     # ./spec/spec_helper.rb:133:in `block (2 levels) in <top (required)>'

Finished in 17 minutes 25 seconds (files took 20.94 seconds to load)
5269 examples, 8 failures, 8 pending

Failed examples:

rspec './spec/jobs/education_form/forms/va1990_spec.rb[1:4:1]' # EducationForm::Forms::VA1990 1990 kitchen_sink_active_duty spool test generates the spool file correctly
rspec './spec/jobs/education_form/forms/va1990_spec.rb[1:2:1]' # EducationForm::Forms::VA1990 1990 kitchen_sink spool test generates the spool file correctly
rspec './spec/jobs/education_form/forms/va1990_spec.rb[1:3:1]' # EducationForm::Forms::VA1990 1990 kitchen_sink_edu_prog spool test generates the spool file correctly
rspec ./modules/vaos/spec/request/messages_request_spec.rb:83 # vaos appointment request messages POST message loa3 user with access and valid message posts a message
rspec ./modules/vaos/spec/request/messages_request_spec.rb:40 # vaos appointment request messages GET messages loa3 user has access and returns messages
rspec './spec/jobs/education_form/forms/va1990e_spec.rb[1:1:1]' # EducationForm::Forms::VA1990e 1990e kitchen_sink spool test generates the spool file correctly
rspec './spec/jobs/education_form/forms/va5490_spec.rb[1:2:1]' # EducationForm::Forms::VA5490 5490 simple_chapter_33_child spool test generates the spool file correctly
rspec './spec/jobs/education_form/forms/va5490_spec.rb[1:5:1]' # EducationForm::Forms::VA5490 5490 kitchen_sink_chapter_35_child spool test generates the spool file correctly

Randomized with seed 62238

Coverage report generated for RSpec to /home/circleci/vets-api/coverage. 31565 / 31936 LOC (98.84%) covered.
SimpleCov failed with exit 1

Exited with code exit status 1
CircleCI received exit code 1

**Comment by johnpaulashenfelter** [comment]
CircleCI
```
$ iconv --version
iconv (Debian GLIBC 2.24-11+deb9u4) 2.24
```

OSX
```
$ iconv --version
iconv (GNU libiconv 1.11)
Copyright (C) 2000-2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Bruno Haible.
```

Staging
```
[dsva@ip-10-247-34-92 ~]$ iconv --version
iconv (GNU libc) 2.17
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Ulrich Drepper.
```

**Comment by johnpaulashenfelter** [comment]
Figured it out. Starting a PR. `i18n.transliterate` ftw

**Comment by johnpaulashenfelter** [comment]
Still two failures.

```
Failures:

  1) vaos appointment request messages POST message loa3 user with access and valid message posts a message
     Failure/Error: expect(response).to have_http_status(:success)
       expected the response to have a success status code (2xx) but it was 500
     # ./modules/vaos/spec/request/messages_request_spec.rb:87:in `block (6 levels) in <top (required)>'
     # ./modules/vaos/spec/request/messages_request_spec.rb:84:in `block (5 levels) in <top (required)>'

  2) vaos appointment request messages GET messages loa3 user has access and returns messages
     Failure/Error: expect(response).to have_http_status(:success)
       expected the response to have a success status code (2xx) but it was 500
     # ./modules/vaos/spec/request/messages_request_spec.rb:44:in `block (5 levels) in <top (required)>'
     # ./modules/vaos/spec/request/messages_request_spec.rb:41:in `block (4 levels) in <top (required)>'

Finished in 0.63209 seconds (files took 20.22 seconds to load)
2 examples, 2 failures

Failed examples:

rspec ./modules/vaos/spec/request/messages_request_spec.rb:83 # vaos appointment request messages POST message loa3 user with access and valid message posts a message
rspec ./modules/vaos/spec/request/messages_request_spec.rb:40 # vaos appointment request messages GET messages loa3 user has access and returns messages
```

They fail reliable for 

`bundle exec rake ci`
`bundle exec rake spec`
`bin/rake spec` with spring

and pass for 

`bundle exec rspec spec`.. — every. time 

After some digging, learned that they both have `:skip_mvi` metadata attribute (thanks @saneshark) but also consistently failing with `rake`.

No current conclusion but have narrowed down the issue signficantly.

**Comment by johnpaulashenfelter** [comment]
Success, but still getting some weird issues with coverage.

https://app.circleci.com/pipelines/github/bkjohnson/vets-api/38/workflows/4c614cfc-7584-43ab-93d4-c12bd946b8af
