### ISSUE TITLE
yarn test:unit does not work in Node v18 (vets-website)

### ISSUE THREAD

**Issue by acald-creator** [department-of-veterans-affairs/va.gov-team#73214]
To make steady progress to move out of Node 14, I'm testing this repo for versions higher than `v16`

Running `yarn test:unit` does not work in `v18`

~- [ ] Research to see why `mocha` does not work, and whether the mocha configuration needs to be revised.~
- [ ] Remove `blob-polyfill`

```bash
yarn run v1.19.1
$ node ./script/run-unit-test.js

✖ ERROR: ReferenceError: document is not defined
    at fixFileAndXHR (/home/acald-creator/va-workspace/vets-website-node/node_modules/blob-polyfill/Blob.js:519:27)
    at /home/acald-creator/va-workspace/vets-website-node/node_modules/blob-polyfill/Blob.js:577:4
    at /home/acald-creator/va-workspace/vets-website-node/node_modules/blob-polyfill/Blob.js:18:4
    at /home/acald-creator/va-workspace/vets-website-node/node_modules/blob-polyfill/Blob.js:23:4
    at Object.<anonymous> (/home/acald-creator/va-workspace/vets-website-node/node_modules/blob-polyfill/Blob.js:690:3)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._compile (/home/acald-creator/va-workspace/vets-website-node/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Object.newLoader [as .js] (/home/acald-creator/va-workspace/vets-website-node/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:202:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:429:15)
    at async exports.requireOrImport (/home/acald-creator/va-workspace/vets-website-node/node_modules/mocha/lib/nodejs/esm-utils.js:42:28)
    at async exports.handleRequires (/home/acald-creator/va-workspace/vets-website-node/node_modules/mocha/lib/cli/run-helpers.js:94:28)
    at async /home/acald-creator/va-workspace/vets-website-node/node_modules/mocha/lib/cli/run.js:349:25
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by acald-creator** [comment]
The test repo I have will still use `mocha` with `enzyme`, but majority of the tests will fail so it is necessary to convert all in order to get most of them to pass.
