### ISSUE TITLE
`test:watch` does not work

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#7639]
The vets-website `test:watch` command does not work. It results in the following output:

```
❯ yarn test:watch
yarn run v1.12.3
$ node script/watch.js
Performing initial set up
Running 887 unit test files
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'babel-polyfill'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/erikhansen/adhoc/vets-website/script/mocha.js:9:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
✨  Done in 0.92s.
```

**Comment by meganhkelley** [comment]
This works now
