### ISSUE TITLE
[FE] - Fix skipped unit test

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#77029]
Fix this skipped unit test. 
- vets-website/src/applications/check-in/hooks/tests/useSendTravelPayClaim/useSendTravelPayClaim.unit.spec.jsx

**Comment by loripusey** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/77029?planning-poker) with Zenhub @wullaski

**Comment by ndouglas** [comment]
The skip was introduced in this PR:

https://github.com/department-of-veterans-affairs/vets-website/pull/25623

Oh, indeed:

```
$ yarn test:unit src/applications/check-in/hooks/tests/useSendTravelPayClaim/useSendTravelPayClaim.unit.spec.jsx
yarn run v1.19.1
$ node ./script/run-unit-tests-local.js src/applications/check-in/hooks/tests/useSendTravelPayClaim/useSendTravelPayClaim.unit.spec.jsx

running:  src/applications/check-in/hooks/tests/useSendTravelPayClaim/useSendTravelPayClaim.unit.spec.jsx
  [▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬]

  0 passing (65ms)
  1 failing

  1) check-in
       useSendTravelPayClaim hook
         Loads test component with hook:
     AssertError: expected postDayOfTravelPayClaim to be called once but was called 0 times
      at Object.fail (node_modules/sinon/lib/sinon/assert.js:96:21)
      at failAssertion (node_modules/sinon/lib/sinon/assert.js:55:16)
      at Object.calledOnce (node_modules/sinon/lib/sinon/assert.js:80:13)
      at Context.<anonymous> (src/applications/check-in/hooks/tests/useSendTravelPayClaim/useSendTravelPayClaim.unit.spec.jsx:63:22)
      at Test.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

How flaky is it? Very flaky; it failed ten times in ten runs.

Digging deeper! ⛏️

**Comment by ndouglas** [comment]
Yesterday I think I established that there's something happening when certain non-`check-in` tests and `check-in` tests run intermingled, but I don't know enough to be able to tell where the problem is.

So I'll list the non-`check-in` tests and see if I can do kind of a binary search to figure out which tests lead to a problem and which do not.

Specifically, the following expression seems to list tests that, when run with `check-in` tests, cause unexpected failures:

```bash
find src/applications -type f -path '*appeals*' -name '*.unit.spec.*'
```

Because I was writing this lazily yesterday, this doesn't just match `src/applications/appeals`, but files with the following general patterns:

```
src/applications/personalization/dashboard/...
src/applications/appeals/996/...
src/applications/appeals/shared/...
src/applications/appeals/995/...
src/applications/appeals/10182/...
src/applications/claims-status/...
```

So quite a few different patterns, but with a binary search I should be able to narrow this down.

- `*applications/claims-status*` fails 0 times out of 10.
- `*applications/personalization*` fails 0 times out of 10.

Very interesting. So that leaves us with `src/applications/appeals`, which fails 4 times out of 10. That aligns with the 38/100 failures we saw yesterday, so we're zeroing in (slowly).

- `*applications/appeals/995*` fails 5 times out of 10.
- `*applications/appeals/996*` fails 6 times out of 10.
- `*applications/appeals/10182*` fails 6 times out of 10.
- `*applications/appeals/shared*` fails 10 times out of 10.

Plucking a random test file out of `applications/appeals/shared`: `src/applications/appeals/shared/tests/content/areaOfDisagreement.unit.spec.jsx`

and running it:

```bash
yarn test:unit src/applications/check-in/components/tests/AddressBlock.unit.spec.jsx src/applications/appeals/shared/tests/content/areaOfDisagreement.unit.spec.jsx
```

we get a failure. Run 100 times, we get 100 failures.

Oh. Turns out there's an issue with the AddressBlock test. It fails when run alone because that doesn't trigger the CheckInProvider, which seems to be reused during tests? 🤔 

That's separate from the issue I'm working on currently, so I'll deal with it separately.

Another `check-in` file, `check-in/day-of/pages/tests/Demographics.unit.spec.jsx`, passes reliably by itself but flakily with `appeals` tests.

Running the tests in a specific order seems to fail reliably:

```bash
yarn test:unit \
  ./src/applications/appeals/shared/tests/components/ContestableIssues.unit.spec.jsx \
  ./src/applications/appeals/shared/tests/utils/data.unit.spec.js \
  ./src/applications/appeals/shared/tests/components/AreaOfDisagreement.unit.spec.jsx \
  ./src/applications/appeals/shared/tests/content/areaOfDisagreement.unit.spec.jsx \
  ./src/applications/appeals/shared/tests/content/reviewErrors.unit.spec.js \
  ./src/applications/appeals/shared/tests/components/NeedsTpVerify.unit.spec.jsx \
  ./src/applications/appeals/shared/tests/validations/contactInfo.unit.spec.js \
  ./src/applications/appeals/shared/tests/utils/issues.unit.spec.js \
  ./src/applications/appeals/shared/tests/utils/dates.unit.spec.js \
  ./src/applications/appeals/shared/tests/components/VeteranInformation.unit.spec.jsx \
  ./src/applications/appeals/shared/tests/utils/areaOfDisagreement.unit.spec.js \
  ./src/applications/appeals/shared/tests/validations/areaOfDisagreements.unit.spec.js \
  ./src/applications/appeals/shared/tests/components/ShowIssuesList.unit.spec.jsx \
  ./src/applications/appeals/shared/tests/utils/upload.unit.spec.js \
  ./src/applications/check-in/day-of/pages/tests/Demographics.unit.spec.jsx \
  ./src/applications/appeals/shared/tests/pages/areaOfDisagreement.unit.spec.jsx \
  ./src/applications/appeals/shared/tests/utils/helpers.unit.spec.js \
  ./src/applications/appeals/shared/tests/validations/issues.unit.spec.js \
  ./src/applications/appeals/shared/tests/content/contestableIssues.unit.spec.jsx \
  ./src/applications/appeals/shared/tests/utils/submit.unit.spec.js \
  ./src/applications/appeals/shared/tests/utils/focus.unit.spec.js \
  ./src/applications/appeals/shared/tests/validations/index.unit.spec.js \
  ./src/applications/appeals/shared/tests/components/AddIssue.unit.spec.js
```

So from there, it's just a matter of popping out files to find what changes will cause it to pass reliably and which will cause it to fail reliably.

We can quickly prune it down to this reliably failing case:

```
yarn test:unit \
  ./src/applications/check-in/day-of/pages/tests/Demographics.unit.spec.jsx \
  ./src/applications/appeals/shared/tests/pages/areaOfDisagreement.unit.spec.jsx
```

That fails, while the following passes reliably:

```
yarn test:unit \
  ./src/applications/appeals/shared/tests/pages/areaOfDisagreement.unit.spec.jsx \
  ./src/applications/check-in/day-of/pages/tests/Demographics.unit.spec.jsx
```

The `areaOfDisagreement` file is brief and simple enough:

```javascript
import React from 'react';
import { expect } from 'chai';
import { render } from '@testing-library/react';

import { DefinitionTester } from '@department-of-veterans-affairs/platform-testing/schemaform-utils';
import { $ } from 'platform/forms-system/src/js/utilities/ui';

import formConfig from '../../../10182/config/form';

describe('area of disagreement page', () => {
  const {
    schema,
    uiSchema,
    arrayPath,
  } = formConfig.chapters.conditions.pages.areaOfDisagreementFollowUp;

  it('should render', () => {
    const { container } = render(
      <DefinitionTester
        definitions={{}}
        arrayPath={arrayPath}
        pagePerItemIndex={0}
        schema={schema}
        uiSchema={uiSchema}
        data={{
          areaOfDisagreement: [
            {
              issue: 'blah',
              decisionDate: '2022-02-02',
            },
            {
              attributes: {
                ratingIssueSubjectText: 'Tinnitus',
                approxDecisionDate: '2021-01-01',
              },
            },
          ],
        }}
      />,
    );

    // This is rendering the uiSchema, so no CustomPage components
    const header = $('h3', container);
    expect(header.id).to.contain('disagreement-title');
    // issueTitle isn't called with form data, so we check the static text
    expect(header.textContent).to.contain('Disagreement with');
    expect(header.textContent).to.contain('decision on');
    expect($('h3 .dd-privacy-hidden[data-dd-action-name]', container)).to.exist;
  });
});
```

By commenting out certain things, we can grope our way toward the culprit:

```javascript
import formConfig from '../../../10182/config/form';
```

If you comment out everything but the above line, the check-in test will still fail. If it is commented out, it will pass.

So following that to `src/applications/appeals/10182/config/form.js`, we find that either of the two following lines are sufficient to cause the test to fail:

```
import { onFormLoaded } from '../utils/redirect';

import IntroductionPage from '../containers/IntroductionPage';
```

After a _lot_ of digging, I found that commenting this line out in `src/platform/forms/save-in-progress/SaveInProgressDevModal.jsx` is sufficient to allow the test to pass.

```
import '@department-of-veterans-affairs/component-library/i18n-setup';
```

That line was added in this PR: https://github.com/department-of-veterans-affairs/vets-website/pull/24883

Past that, I'm having some trouble figuring out what's going on. I can see that when I comment out the `resources` section of `i18n-setup.js`, that this problem stops occurring... but beyond that, it gets really fuzzy really fast. Not sure if brain is cooked or if I'm just past the limits of my ability to debug JavaScript. VS Code dies whenever I try to attach the debugger 😩

**Comment by ndouglas** [comment]
The `Demographics` test imports `src/applications/check-in/tests/unit/utils/CheckInProvider.jsx`, which imports `src/applications/check-in/utils/i18n/i18n.js`. 

The latter sets up translation as follows:

```javascript
// Imports this English translation
import enTranslation from '../../locales/en/translation.json';
...
  i18n
    .use(initReactI18next)
    .use(LanguageDetector)
    .init({...});
...
export default i18n;
```

I rewrote this slightly to perform the setup in a function:

```javascript
...
export const setupI18n = () => {
  i18n...
  ...
  // This is necessary for DS components to use our language preference on initial page load.
  i18n.on('languageChanged', language => {
    setPageLanguage(language);
  });
};

...

/**
 * Cleans up i18n setup to avoid interference between tests.
 */
export const teardownI18n = () => {
  i18n.off('languageChanged', setPageLanguage);
  // i18n.reset();
};
```

And I updated CheckInProvider accordingly:

```
import React from 'react';
import PropTypes from 'prop-types';
import { Provider } from 'react-redux';
import { I18nextProvider } from 'react-i18next';

import { createStore } from './initState';
import { createMockRouter } from '../mocks/router';

const CheckInProvider = ({ i18n, children, store = {}, router = {} }) => {
  const initStore = createStore(store);
  const defaultRouter = {
    params: {
      token: 'token-123',
    },
    currentPage: '/test-page',
  };
  const mockRouter = { ...defaultRouter, ...router };
  const initRouter = createMockRouter(mockRouter);
  return (
    <Provider store={initStore}>
      <I18nextProvider i18n={i18n}>
        {React.cloneElement(children, { router: initRouter })}
      </I18nextProvider>
    </Provider>
  );
};

CheckInProvider.propTypes = {
  i18n: PropTypes.object.isRequired,
  children: PropTypes.node,
  router: PropTypes.object,
  store: PropTypes.object,
};

export default CheckInProvider;
```

and then the Demographics test:

```
import React from 'react';
import { render } from '@testing-library/react';
import { expect } from 'chai';
import sinon from 'sinon';

import CheckInProvider from '../../../tests/unit/utils/CheckInProvider';
import { setupI18n, teardownI18n } from '../../../utils/i18n/i18n';
import Demographics from '../Demographics';

describe('check in', () => {
  beforeEach(() => {
    setupI18n();
  });

  afterEach(() => {
    teardownI18n();
  });

  describe('Demographics', () => {
    const veteranData = {
      demographics: {
        mailingAddress: {
          street1: '123 Turtle Trail',
          city: 'Treetopper',
          state: 'Tennessee',
          zip: '101010',
        },
        homeAddress: {
          street1: '445 Fine Finch Fairway',
          street2: 'Apt 201',
          city: 'Fairfence',
          state: 'Florida',
          zip: '445545',
        },
        homePhone: '5552223333',
        mobilePhone: '5553334444',
        workPhone: '5554445555',
        emailAddress: 'kermit.frog@sesameenterprises.us',
      },
    };
    it('renders', () => {
      const component = render(
        <CheckInProvider store={{ veteranData }}>
          <Demographics />
        </CheckInProvider>,
      );

      expect(component.getByText('Is this your current contact information?'))
        .to.exist;
      expect(component.getByText('445 Fine Finch Fairway')).to.exist;
      expect(component.queryByText('Not available')).to.be.null;
    });
    ...
  });
});
```

Now tests will pass when the files are executed in either order:

```bash
🔔nathan.douglas@Nathan-Douglas:~/Projects/vets-website
$ yarn test:unit   ./src/applications/check-in/day-of/pages/tests/Demographics.unit.spec.jsx   ./src/applications/appeals/shared/tests/pages/areaOfDisagreement.unit.spec.jsx
yarn run v1.19.1
$ node ./script/run-unit-tests-local.js ./src/applications/check-in/day-of/pages/tests/Demographics.unit.spec.jsx ./src/applications/appeals/shared/tests/pages/areaOfDisagreement.unit.spec.jsx
DOM fully loaded and parsed

running:  src/applications/check-in/day-of/pages/tests/Demographics.unit.spec.jsx
  [▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬.............................................................................]running:  src/applications/check-in/day-of/pages/tests/Demographics.unit.spec.jsx
  [▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬..........................................................]running:  src/applications/check-in/day-of/pages/tests/Demographics.unit.spec.jsx
  [▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬......................................]running:  src/applications/check-in/day-of/pages/tests/Demographics.unit.spec.jsx
  [▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬...................]running:  src/applications/appeals/shared/tests/pages/areaOfDisagreement.unit.spec.jsx
  [▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬]

  5 passing (238ms)

✨  Done in 9.68s.
🔔nathan.douglas@Nathan-Douglas:~/Projects/vets-website
$ yarn test:unit ./src/applications/appeals/shared/tests/pages/areaOfDisagreement.unit.spec.jsx  ./src/applications/check-in/day-of/pages/tests/Demographics.unit.spec.jsx 
yarn run v1.19.1
$ node ./script/run-unit-tests-local.js ./src/applications/appeals/shared/tests/pages/areaOfDisagreement.unit.spec.jsx ./src/applications/check-in/day-of/pages/tests/Demographics.unit.spec.jsx
DOM fully loaded and parsed

running:  src/applications/appeals/shared/tests/pages/areaOfDisagreement.unit.spec.jsx
  [▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬.............................................................................]running:  src/applications/check-in/day-of/pages/tests/Demographics.unit.spec.jsx
  [▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬..........................................................]running:  src/applications/check-in/day-of/pages/tests/Demographics.unit.spec.jsx
  [▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬......................................]running:  src/applications/check-in/day-of/pages/tests/Demographics.unit.spec.jsx
  [▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬...................]running:  src/applications/check-in/day-of/pages/tests/Demographics.unit.spec.jsx
  [▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬]

  5 passing (230ms)

✨  Done in 7.72s.
🔔nathan.douglas@Nathan-Douglas:~/Projects/vets-website
$
```

Obviously this breaks a lot of things elsewhere, and I'm not sure if it's idiomatic, but I can figure out what other changes need to be made and go from there if the basic approach is sound.

Unfortunately, I need to go to Cleveland, so the rest will need to wait until this afternoon.
