### ISSUE TITLE
Support alert assertions in VAOS unit tests

### ISSUE THREAD

**Issue by JunTaoLuo** [department-of-veterans-affairs/va.gov-team#82624]
## Summary
- Tests involved
  - VAOS Page: TypeOfVisitPage - should not submit empty form
  - VAOS Page: ClosestCityStatePage - should not submit without choosing a site
- Issues or enhancements involving test infrastructure and libraries

Currently alerts from validation is difficult to write assertions for in certain unit tests since the DOM does not update after user action (e.g. clicking a button or choosing an option) is made. Ideally we should be able to assert alerts are displayed correctly to ensure the desired component behaviors.

## Steps to Reproduce
- Enable the disabled assertions in the test that link to this issue and the test will fail

### Actual Result
Currently these assertions are disabled so no errors are observed but enabling the assertions will result in the following stack traces:

<details>
  <summary>Expand stack trace</summary>

```
  1) VAOS Page: ClosestCityStatePage
       should not submit without choosing a site:
     Unable to find role="alert"

<body>
  <div>
    <div>
      <form
        class="rjsf"
        novalidate=""
      >
        <div
          class="vads-u-margin-y--2 rjsf-object-field"
        >
          <div>
            <va-radio
              class="rjsf-web-component-field vads-u-margin-top--neg2"
              error="Select a city"
              label="What’s the nearest city to you?"
              label-header-level="1"
              name="root_communityCareSystemId"
              required="true"
              uswds="true"
              value="false"
            >
              <div
                slot="description"
              />
              <va-radio-option
                checked="false"
                label="Bozeman, MT"
                name="root_communityCareSystemId"
                uswds="true"
                value="983"
              />
              <va-radio-option
                checked="false"
                label="Belgrade, MT"
                name="root_communityCareSystemId"
                uswds="true"
                value="983GC"
              />
            </va-radio>
          </div>
        </div>
        <va-additional-info
          class="vads-u-margin-bottom--4"
          data-testid="additional-info"
          trigger="Why we’re asking this"
        >
          <div>
            We'll send your request to the VA medical center nearest to the city you select. The medical center staff will help schedule your community care appointment.

          </div>
        </va-additional-info>
        <div
          class="vads-l-row form-progress-buttons schemaform-buttons"
        >
          <div
            class="vaos__form-button-back xsmall-screen:vads-u-padding-right--1p5 medium-screen:vads-u-padding-right--0p5"
          >
            <button
              class="usa-button-secondary"
              id="98-continueButton"
              type="button"
            >
              <i
                aria-hidden="true"
                class="fa fa-angles-left"
              />
              Back

            </button>
          </div>
          <div
            class="vaos__form-button-next"
          >
            <button
              aria-label="Continue"
              aria-live="polite"
              class="usa-button usa-button-primary"
              type="submit"
            >
              Continue »
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>
</body>

<body>
  <div>
    <div>
      <form
        class="rjsf"
        novalidate=""
      >
        <div
          class="vads-u-margin-y--2 rjsf-object-field"
        >
          <div>
            <va-radio
              class="rjsf-web-component-field vads-u-margin-top--neg2"
              error="Select a city"
              label="What’s the nearest city to you?"
              label-header-level="1"
              name="root_communityCareSystemId"
              required="true"
              uswds="true"
              value="false"
            >
              <div
                slot="description"
              />
              <va-radio-option
                checked="false"
                label="Bozeman, MT"
                name="root_communityCareSystemId"
                uswds="true"
                value="983"
              />
              <va-radio-option
                checked="false"
                label="Belgrade, MT"
                name="root_communityCareSystemId"
                uswds="true"
                value="983GC"
              />
            </va-radio>
          </div>
        </div>
        <va-additional-info
          class="vads-u-margin-bottom--4"
          data-testid="additional-info"
          trigger="Why we’re asking this"
        >
          <div>
            We'll send your request to the VA medical center nearest to the city you select. The medical center staff will help schedule your community care appointment.

          </div>
        </va-additional-info>
        <div
          class="vads-l-row form-progress-buttons schemaform-buttons"
        >
          <div
            class="vaos__form-button-back xsmall-screen:vads-u-padding-right--1p5 medium-screen:vads-u-padding-right--0p5"
          >
            <button
              class="usa-button-secondary"
              id="98-continueButton"
              type="button"
            >
              <i
                aria-hidden="true"
                class="fa fa-angles-left"
              />
              Back

            </button>
          </div>
          <div
            class="vaos__form-button-next"
          >
            <button
              aria-label="Continue"
              aria-live="polite"
              class="usa-button usa-button-primary"
              type="submit"
            >
              Continue »
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>
</body>
  Error: Unable to find role="alert"

  <body>
    <div>
      <div>
        <form
          class="rjsf"
          novalidate=""
        >
          <div
            class="vads-u-margin-y--2 rjsf-object-field"
          >
            <div>
              <va-radio
                class="rjsf-web-component-field vads-u-margin-top--neg2"
                error="Select a city"
                label="What’s the nearest city to you?"
                label-header-level="1"
                name="root_communityCareSystemId"
                required="true"
                uswds="true"
                value="false"
              >
                <div
                  slot="description"
                />
                <va-radio-option
                  checked="false"
                  label="Bozeman, MT"
                  name="root_communityCareSystemId"
                  uswds="true"
                  value="983"
                />
                <va-radio-option
                  checked="false"
                  label="Belgrade, MT"
                  name="root_communityCareSystemId"
                  uswds="true"
                  value="983GC"
                />
              </va-radio>
            </div>
          </div>
          <va-additional-info
            class="vads-u-margin-bottom--4"
            data-testid="additional-info"
            trigger="Why we’re asking this"
          >
            <div>
              We'll send your request to the VA medical center nearest to the city you select. The medical center staff will help schedule your community care appointment.

            </div>
          </va-additional-info>
          <div
            class="vads-l-row form-progress-buttons schemaform-buttons"
          >
            <div
              class="vaos__form-button-back xsmall-screen:vads-u-padding-right--1p5 medium-screen:vads-u-padding-right--0p5"
            >
              <button
                class="usa-button-secondary"
                id="98-continueButton"
                type="button"
              >
                <i
                  aria-hidden="true"
                  class="fa fa-angles-left"
                />
                Back

              </button>
            </div>
            <div
              class="vaos__form-button-next"
            >
              <button
                aria-label="Continue"
                aria-live="polite"
                class="usa-button usa-button-primary"
                type="submit"
              >
                Continue »
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </body>
      at waitForWrapper (node_modules/@testing-library/dom/dist/wait-for.js:173:27)
      at findByRole (node_modules/@testing-library/dom/dist/query-helpers.js:101:33)
      at _callee2$ (src/applications/vaos/tests/new-appointment/components/ClosestCityStatePage.unit.spec.js:75:25)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:294:22)
      at Generator.next (node_modules/regenerator-runtime/runtime.js:119:21)
      at asyncGeneratorStep (src/applications/vaos/tests/new-appointment/components/ClosestCityStatePage.unit.spec.js:19:103)
      at _next (src/applications/vaos/tests/new-appointment/components/ClosestCityStatePage.unit.spec.js:21:194)
```
</details>

## Definition of Done
- [ ] Root cause for test failure is found
- [ ] Test is updated or fixed

**Comment by ldelacosta** [comment]
Assigning the ticket @JunTaoLuo and @simiadebowale for awareness. Please move it to the Ready queue when the team can start on the work. cc: @JRRoof

**Comment by JunTaoLuo** [comment]
We've decided that these assertions should be made in Cypress E2E tests. As a result, we'll file tickets to convert these tests from unit tests to E2E tests instead.
