### ISSUE TITLE
VAOS flaky test: VAOS Page: ContactInfoPage should accept email, phone, and preferred time and continue

### ISSUE THREAD

**Issue by JunTaoLuo** [department-of-veterans-affairs/va.gov-team#82968]
# 1. Test failure or skipped test

- "VAOS Page: ContactInfoPage should accept email, phone, and preferred time and continue" is flaky and has been disabled. This issue tracks the investigation for this test failure and eventually re-enabling this test.
- The test is flaky locally. Although I haven't seen this happen on the CI yet, I suspect it will also be flaky there as well.
- Note that this may be a product issue since the test is almost identical to the following test in the covid-19 ContactInfoPage test suite which passes reliably:
https://github.com/department-of-veterans-affairs/vets-website/blob/e0ef6a3a5085bd1f916160cda1150cf0c992b274/src/applications/vaos/tests/covid-19-vaccine/components/ContactInfoPage.unit.spec.js#L10

## Steps to Reproduce
- Re-enable the test and run the entire VAOS test suite using the command `yarn test:unit --app-folder vaos`. The test seems to pass more reliably when run in isolation.

### Actual Result
Here's the error message for the test failure:
```
  1) VAOS Page: ContactInfoPage
       should accept email, phone, and preferred time and continue:
       
      AssertionError: expected false to be true
      + expected - actual

      -false
      +true

      at _callee$ (src/applications/vaos/tests/new-appointment/components/ContactInfoPage.unit.spec.js:53:5)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:294:22)
      at Generator.next (node_modules/regenerator-runtime/runtime.js:119:21)
      at asyncGeneratorStep (src/applications/vaos/tests/new-appointment/components/ContactInfoPage.unit.spec.js:25:103)
      at _next (src/applications/vaos/tests/new-appointment/components/ContactInfoPage.unit.spec.js:27:194)
```

## Definition of Done
- [ ] Root cause for test failure is found
- [ ] Test is updated or fixed

---
## How to configure this issue
- [ ] **Labeled with Team** (`appointments`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `design`, `product`)
- [ ] **Labeled with** `testing`
- [ ] **Assigned to** Product for prioritization

**Comment by jenniemc** [comment]
No validation needed for unit test. Closing this ticket.
