### ISSUE TITLE
[FSR] Bugfix Employment history

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#87575]
Here's the Exception:
```
 "meta": { "exception": "no implicit conversion of String into Integer",
 "backtrace": [
     "/usr/local/bundle/cache/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/hash_with_indifferent_access.rb:210:in `dig'",
     "/usr/local/bundle/cache/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/hash_with_indifferent_access.rb:210:in `dig'",
     "/usr/local/bundle/cache/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/hash_with_indifferent_access.rb:210:in `dig'",
     "/usr/local/bundle/cache/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/hash_with_indifferent_access.rb:210:in `dig'",
     "/app/modules/debts_api/lib/debts_api/v0/fsr_form_transform/income_calculator.rb:29:in `initialize'",
     "/app/modules/debts_api/lib/debts_api/v0/fsr_form_transform/full_transform_service.rb:22:in `new'",
     "/app/modules/debts_api/lib/debts_api/v0/fsr_form_transform/full_transform_service.rb:22:in `initialize'",
     "/app/modules/debts_api/app/controllers/debts_api/v0/financial_status_reports_controller.rb:307:in `new'",
     "/app/modules/debts_api/app/controllers/debts_api/v0/financial_status_reports_controller.rb:307:in `full_transform_service'",
     "/app/modules/debts_api/app/controllers/debts_api/v0/financial_status_reports_controller.rb:20:in `transform_and_submit'",
   ...
 ],
}
```

The issue seems to be that the initializer is expecting a different data structure in this file:
`modules/debts_api/lib/debts_api/v0/fsr_form_transform/income_calculator.rb:29`

When we dig into the data, we try and go into an array like it's a hash:
```
pry(#<DebtsApi::V0::FsrFormTransform::IncomeCalculator>)> @vet_employment_records = @form.dig('personal_data', 'employment_history')
=> [{"veteran_or_spouse"=>"VETERAN",
  "occupation_name"=>"Full time",
  "from"=>"01/2018",
  "to"=>"",
  "present"=>true,
  "employer_name"=>"Testing",
  "employer_address"=>{"addressline_one"=>"", "addressline_two"=>"", "addressline_three"=>"", "city"=>"", "state_or_province"=>"", "zip_or_postal_code"=>"", "country_name"=>""}}]
```

```
pry(#<DebtsApi::V0::FsrFormTransform::IncomeCalculator>)> @vet_employment_records = @form.dig('personal_data', 'employment_history', 'veteran', 'employment_records')
TypeError: no implicit conversion of String into Integer
```

**Comment by digitaldrk** [comment]
This one is blocked until we sort out the frontend payload
