### ISSUE TITLE
[FSR transform] Streamlined Long Exception

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#88509]

**Comment by digitaldrk** [comment]
Andrew got an exception submitting an FSR locally we need to run down the issue and remedy so we can launch.

## Exception
```
{
    "errors": [
        {
            "title": "Internal server error",
            "detail": "Internal server error",
            "code": "500",
            "status": "500",
            "meta": {
                "exception": "comparison of Float with nil failed",
                "backtrace": [
                    "/app/modules/debts_api/lib/debts_api/v0/fsr_form_transform/streamlined_calculator.rb:84:in `<'",
                    "/app/modules/debts_api/lib/debts_api/v0/fsr_form_transform/streamlined_calculator.rb:84:in `income_below_upper_threshold?'",
                    "/app/modules/debts_api/lib/debts_api/v0/fsr_form_transform/streamlined_calculator.rb:63:in `meets_streamlined_long_form_common_conditions?'",
                    "/app/modules/debts_api/lib/debts_api/v0/fsr_form_transform/streamlined_calculator.rb:53:in `streamlined_long_form?'",
                    "/app/modules/debts_api/lib/debts_api/v0/fsr_form_transform/streamlined_calculator.rb:30:in `get_streamlined_data'",
                    "/app/modules/debts_api/lib/debts_api/v0/fsr_form_transform/full_transform_service.rb:34:in `initialize'",
                    "/app/modules/debts_api/app/controllers/debts_api/v0/financial_status_reports_controller.rb:307:in `new'",
                    "/app/modules/debts_api/app/controllers/debts_api/v0/financial_status_reports_controller.rb:307:in `full_transform_service'",
                    "/app/modules/debts_api/app/controllers/debts_api/v0/financial_status_reports_controller.rb:20:in `transform_and_submit'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/abstract_controller/base.rb:224:in `process_action'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_controller/metal/rendering.rb:165:in `process_action'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/abstract_controller/callbacks.rb:259:in `block in process_action'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:110:in `run_callbacks'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/abstract_controller/callbacks.rb:258:in `process_action'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_controller/metal/rescue.rb:25:in `process_action'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_controller/metal/instrumentation.rb:74:in `block in process_action'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/notifications.rb:206:in `block in instrument'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/notifications/instrumenter.rb:58:in `instrument'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/notifications.rb:206:in `instrument'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_controller/metal/instrumentation.rb:73:in `process_action'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_controller/metal/params_wrapper.rb:261:in `process_action'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/railties/controller_runtime.rb:32:in `process_action'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/abstract_controller/base.rb:160:in `process'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_controller/metal.rb:227:in `dispatch'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_controller/metal.rb:309:in `dispatch'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/routing/route_set.rb:32:in `serve'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/journey/router.rb:51:in `block in serve'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/journey/router.rb:131:in `block in find_routes'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/journey/router.rb:124:in `each'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/journey/router.rb:124:in `find_routes'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/journey/router.rb:32:in `serve'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/routing/route_set.rb:882:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/engine.rb:536:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/railtie.rb:226:in `public_send'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/railtie.rb:226:in `method_missing'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/routing/mapper.rb:22:in `block in <class:Constraints>'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/routing/mapper.rb:51:in `serve'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/journey/router.rb:51:in `block in serve'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/journey/router.rb:131:in `block in find_routes'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/journey/router.rb:124:in `each'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/journey/router.rb:124:in `find_routes'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/journey/router.rb:32:in `serve'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/routing/route_set.rb:882:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/coverband-6.1.2/lib/coverband/integrations/background_middleware.rb:10:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/rack-attack-6.7.0/lib/rack/attack.rb:103:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/rack-2.2.9/lib/rack/session/abstract/id.rb:266:in `context'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/rack-2.2.9/lib/rack/session/abstract/id.rb:260:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/middleware/cookies.rb:689:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/rack-attack-6.7.0/lib/rack/attack.rb:127:in `call'",
                    "/app/lib/statsd_middleware.rb:156:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/olive_branch-4.0.1/lib/olive_branch/middleware.rb:64:in `call'",
                    "/app/lib/olive_branch_patch.rb:9:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/rack-2.2.9/lib/rack/etag.rb:27:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/rack-2.2.9/lib/rack/conditional_get.rb:40:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/rack-2.2.9/lib/rack/head.rb:12:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:101:in `run_callbacks'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/middleware/callbacks.rb:28:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/middleware/executor.rb:14:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/middleware/actionable_exceptions.rb:16:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/web-console-4.2.1/lib/web_console/middleware.rb:132:in `call_app'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/web-console-4.2.1/lib/web_console/middleware.rb:19:in `block in call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/web-console-4.2.1/lib/web_console/middleware.rb:17:in `catch'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/web-console-4.2.1/lib/web_console/middleware.rb:17:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/rack/logger.rb:37:in `call_app'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/rack/logger.rb:24:in `block in call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/semantic_logger-4.16.0/lib/semantic_logger/base.rb:190:in `block in tagged'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/semantic_logger-4.16.0/lib/semantic_logger/semantic_logger.rb:346:in `tagged'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/semantic_logger-4.16.0/lib/semantic_logger/base.rb:202:in `tagged'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/rack/logger.rb:24:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/middleware/remote_ip.rb:92:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/request_store-1.7.0/lib/request_store/middleware.rb:19:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/middleware/request_id.rb:28:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/rack-2.2.9/lib/rack/runtime.rb:22:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/rack-timeout-0.7.0/lib/rack/timeout/core.rb:154:in `block in call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/rack-timeout-0.7.0/lib/rack/timeout/support/timeout.rb:19:in `timeout'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/rack-timeout-0.7.0/lib/rack/timeout/core.rb:153:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/middleware/executor.rb:14:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/middleware/static.rb:25:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/rack-2.2.9/lib/rack/sendfile.rb:110:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/middleware/host_authorization.rb:141:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/rack-cors-2.0.2/lib/rack/cors.rb:102:in `call'",
                    "/app/lib/http_method_not_allowed.rb:13:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/utf8-cleaner-1.0.0/lib/utf8-cleaner/middleware.rb:21:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/engine.rb:536:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/puma-6.4.2/lib/puma/configuration.rb:272:in `call'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/puma-6.4.2/lib/puma/request.rb:100:in `block in handle_request'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/puma-6.4.2/lib/puma/thread_pool.rb:378:in `with_force_shutdown'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/puma-6.4.2/lib/puma/request.rb:99:in `handle_request'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/puma-6.4.2/lib/puma/server.rb:464:in `process_client'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/puma-6.4.2/lib/puma/server.rb:245:in `block in run'",
                    "/usr/local/bundle/cache/ruby/3.3.0/gems/puma-6.4.2/lib/puma/thread_pool.rb:155:in `block in spawn_thread'"
                ]
            }
        }
    ]
}
```
