### ISSUE TITLE
[DevOps] Replace LoROTA validateBody validation with JSON schema validation.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#89392]
## Description
This will require fixing some tests as noted in a comment below.

## Tasks
- [ ] [DevOps] **_insert DevOps work_**

**Comment by ndouglas** [comment]
With some hacky changes:

```
diff --git a/src/packages/utils/commonUtils.js b/src/packages/utils/commonUtils.js
index 581c98a..c7428ee 100644
--- a/src/packages/utils/commonUtils.js
+++ b/src/packages/utils/commonUtils.js
@@ -4,6 +4,18 @@ const CryptoJS = require('crypto-js');
 
 const salt = process.env.HASHING_SALT;
 
+const rootSchema = require('../../../schema/root.json');
+const pciAdditionalValidationSchema = require('../../../schema/additional_validation/pci.json');
+const Ajv = require("ajv");
+const addFormats = require("ajv-formats");
+
+const ajv = new Ajv({
+  $data: true,
+});
+addFormats(ajv);
+ajv.addSchema(pciAdditionalValidationSchema);
+const validate = ajv.compile(rootSchema);
+
 const generateResponse = (statusCode, responseBody) => ({
   body: JSON.stringify(responseBody),
   statusCode,
@@ -29,6 +41,10 @@ const validateBody = (requestBody) => {
     return { error: 'request body is empty' };
   }
   const body = tryParseJSON(requestBody);
+  const valid = validate(body);
+  if (!valid) {
+    return { error: ajv.errorsText(validate.errors) };
+  }
 
   if (body.error) {
     return { error: body.error };
diff --git a/src/test/tests/unit/utils/commonUtils.test.js b/src/test/tests/unit/utils/commonUtils.test.js
index 9633bbf..c964b55 100644
--- a/src/test/tests/unit/utils/commonUtils.test.js
+++ b/src/test/tests/unit/utils/commonUtils.test.js
@@ -44,7 +44,7 @@ describe('tryParseJSON tests ', () => {
   });
 });
 
-describe('validateBody tests', () => {
+describe.skip('validateBody tests', () => {
   test('function test', () => {
     expect(typeof validateBody).toBe('function');
   });

```

```
  ● put lambda success tests › update lorota

    expect(jest.fn()).toHaveBeenCalledTimes(expected)

    Expected number of calls: 1
    Received number of calls: 0

      55 |     dynamoDbUtils.updateItem.mockResolvedValue({ Attributes: {} });
      56 |     const response = await putLamba.handler(lambaEvent);
    > 57 |     expect(dynamoDbUtils.updateItem).toHaveBeenCalledTimes(1);
         |                                      ^
      58 |     expect(response.statusCode).toBe(StatusCodes.OK);
      59 |   });
      60 | });

      at Object.<anonymous> (tests/unit/put-data/index.test.js:57:38)

  ● put lambda error tests › missing options

    expect(received).toBe(expected) // Object.is equality

    Expected: "options missing in request body"
    Received: "data must have required property 'options'"

      119 |     const response = await putLamba.handler(lambaEvent);
      120 |     expect(response.statusCode).toBe(StatusCodes.BAD_REQUEST);
    > 121 |     expect(JSON.parse(response.body).error).toBe('options missing in request body');
          |                                             ^
      122 |     expect(dynamoDbUtils.updateItem).toHaveBeenCalledTimes(0);
      123 |   });
      124 |

      at Object.<anonymous> (tests/unit/put-data/index.test.js:121:45)

  ● put lambda error tests › missing payload

    expect(received).toBe(expected) // Object.is equality

    Expected: "payload missing in request body"
    Received: "data must have required property 'payload'"

      141 |     const response = await putLamba.handler(lambaEvent);
      142 |     expect(response.statusCode).toBe(StatusCodes.BAD_REQUEST);
    > 143 |     expect(JSON.parse(response.body).error).toBe('payload missing in request body');
          |                                             ^
      144 |     expect(dynamoDbUtils.updateItem).toHaveBeenCalledTimes(0);
      145 |   });
      146 |

      at Object.<anonymous> (tests/unit/put-data/index.test.js:143:45)

  ● put lambda error tests › missing ValidEnd

    expect(received).toBe(expected) // Object.is equality

    Expected: "validEnd is missing"
    Received: "data/options must have required property 'validStart'"

      164 |     const response = await putLamba.handler(lambaEvent);
      165 |     expect(response.statusCode).toBe(StatusCodes.BAD_REQUEST);
    > 166 |     expect(JSON.parse(response.body).error).toBe('validEnd is missing');
          |                                             ^
      167 |     expect(dynamoDbUtils.updateItem).toHaveBeenCalledTimes(0);
      168 |   });
      169 |

      at Object.<anonymous> (tests/unit/put-data/index.test.js:166:45)

  ● put lambda error tests › missing ValidStart

    expect(received).toBe(expected) // Object.is equality

    Expected: "validStart is missing"
    Received: "data/options must have required property 'validStart'"

      190 |     const response = await putLamba.handler(lambaEvent);
      191 |     expect(response.statusCode).toBe(StatusCodes.BAD_REQUEST);
    > 192 |     expect(JSON.parse(response.body).error).toBe('validStart is missing');
          |                                             ^
      193 |     expect(dynamoDbUtils.updateItem).toHaveBeenCalledTimes(0);
      194 |   });
      195 |

      at Object.<anonymous> (tests/unit/put-data/index.test.js:192:45)

  ● put lambda error tests › validStart > validEnd

    expect(received).toBe(expected) // Object.is equality

    Expected: "validEnd must be greater than validStart"
    Received: "data/options/validStart must be <= 1632757559"

      216 |     const response = await putLamba.handler(lambaEvent);
      217 |     expect(response.statusCode).toBe(StatusCodes.BAD_REQUEST);
    > 218 |     expect(JSON.parse(response.body).error).toBe('validEnd must be greater than validStart');
          |                                             ^
      219 |     expect(dynamoDbUtils.updateItem).toHaveBeenCalledTimes(0);
      220 |   });
      221 |

      at Object.<anonymous> (tests/unit/put-data/index.test.js:218:45)

  ● put lambda error tests › missing id

    expect(jest.fn()).toHaveBeenCalledTimes(expected)

    Expected number of calls: 1
    Received number of calls: 0

      259 |     });
      260 |     const response = await putLamba.handler(lambaEvent);
    > 261 |     expect(dynamoDbUtils.updateItem).toHaveBeenCalledTimes(1);
          |                                      ^
      262 |     expect(response.statusCode).toBe(StatusCodes.NOT_FOUND);
      263 |   });
      264 |

      at Object.<anonymous> (tests/unit/put-data/index.test.js:261:38)

  ● put lambda error tests › database error

    expect(jest.fn()).toHaveBeenCalledTimes(expected)

    Expected number of calls: 1
    Received number of calls: 0

      292 |     dynamoDbUtils.updateItem.mockResolvedValue({ error: 'Requested resource not found' });
      293 |     const response = await putLamba.handler(lambaEvent);
    > 294 |     expect(dynamoDbUtils.updateItem).toHaveBeenCalledTimes(1);
          |                                      ^
      295 |     expect(response.statusCode).toBe(StatusCodes.INTERNAL_SERVER_ERROR);
      296 |   });
      297 | });

      at Object.<anonymous> (tests/unit/put-data/index.test.js:294:38)
```
