### ISSUE TITLE
Remove momentjs from platform downtime component

### ISSUE THREAD

**Issue by dcloud** [department-of-veterans-affairs/va.gov-team#90200]
## Description

Momentjs is deprecated, and the platform downtime component still uses momentjs. We should see if we can remove Moment.js as a dependency from the platform downtime component for all teams.

### User story

As a Cartography team member, I want our application to be small and performant, and removing Momentjs from upstream platform code helps us make our application more performant

### Notes

- I (Daniel) think that Momentjs is used by Appointments (VAOS) for complex datetime needs, so we may want to get buy-in and reviews from that team
- `date-fns` is the preferred tool for datetime manipulation

Possible tasks:
- 

## Acceptance criteria

- Platform downtime component does not use Momentjs
- QA review
- A11y review

**Comment by dcloud** [comment]
Realizing that we also had a note in department-of-veterans-affairs/va.gov-team/issues/75609 that removing momentjs could be done during a refactor

**Comment by kayline** [comment]
Hello! I'm a new engineer working on VA Benefits at Coforma. I was looking at this ticket as something I could work on while I'm getting oriented, and I was wondering if the downtime date values that are passed to this component are expected to be in Eastern Time?

**Comment by dcloud** [comment]
> Hello! I'm a new engineer working on VA Benefits at Coforma. I was looking at this ticket as something I could work on while I'm getting oriented, and I was wondering if the downtime date values that are passed to this component are expected to be in Eastern Time?

@kayline I created this ticket for my team (label: Cartographers) when we were looking at this platform component, but its been a while. In short, I don't think the component expects date values in Eastern time.

When this ticket was created, the component expected momentjs objects, which I believe are similar to native Date objects in that the internal representation would be a Unix timestamp, which is in UTC. It would be up to the app/browser to format that UTC datetime appropriately for end users in various timezones.

**Comment by dcloud** [comment]
Quite a bit of progress after the initial conversion. Uncovering (and attempting to fix) issues in applications that assume DowntimeNotification passes around moment objects rather than Date objects.

- `rg toDate` is helpful. Search for calls to convert from moment obj to native Date obj
-  `rg 'render=' $(rg '\<DowntimeNotification' -l src/applications)`. Search for places where DowntimeNotification is used, then look in those places for `render=`, an indicator of custom downtime rendering

I've been working on CI test errors, though some appear to be CI-specific. I can't reproduce these locally, so far:

```shell
4) getStatusForTimeframe
       assigns a status according to timeframe:

      AssertionError: expected 'ok' to equal 'downtimeApproaching'
      + expected - actual

      -ok
      +downtimeApproaching
      
      at Context.<anonymous> (src/platform/monitoring/DowntimeNotification/tests/helpers.unit.spec.jsx:92:10)
      at Test.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:462:21)
      at process.callbackTrampoline (internal/async_hooks.js:134:14)

  5) createServiceMap
       creates a map using the attributes.externalService property as keys:

      AssertionError: expected 'ok' to equal 'downtimeApproaching'
      + expected - actual

      -ok
      +downtimeApproaching
      
      at Context.<anonymous> (src/platform/monitoring/DowntimeNotification/tests/helpers.unit.spec.jsx:160:27)
      at Test.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:462:21)
      at process.callbackTrampoline (internal/async_hooks.js:134:14)
```

However, looking at these did reveal an issue with the initial conversion that Copilot started. Copilot had hallucinated a function early on, which I caught, but it had also hallucinated about one of the test datetimes. Now things _should_ be okay, but CI still isn't happy. A puzzle for future me.

**Comment by dcloud** [comment]
## Unrelated error investigation

### 2 consoles ???

`src/platform/monitoring/Datadog/tests/useBrowserMonitoring.unit.spec.jsx:140` appears to point to an issue with a [sinon stub](https://sinonjs.org/releases/v20/stubs/) of `console`. But JSDOM, which is used by the mocha test runner, appears to set up a [virtual console](https://github.com/jsdom/jsdom?tab=readme-ov-file#virtual-consoles) attached to the `window` object. So it _might_ be that there are 2 different consoles, one virtual via JSDOM, the other from NodeJS.

This only appears to affect one of the tests, but uncertain

### 2 different test scripts

> there’s also effectively two scripts that handle the test running:
> script/github-actions/run-unit-tests-gha.js
> script/run-unit-tests-local.js

So tests are run differently in CI vs locally. Interesting

**Comment by dcloud** [comment]
PR merged by Platform, overriding unrelated failing tests issue. Contingent on whether failing tests spread to other PRs, aka "if something goes wrong, be prepared to revert"
