### ISSUE TITLE
Pension | remediate sidekiq exhaustion 9/27

### ISSUE THREAD

**Issue by wayne-weibel** [department-of-veterans-affairs/va.gov-team#93846]
saved claim id - 9913308

exhaustion due to malformed attachment pdf attempting to be datestamped/watermarked

https://dsva.slack.com/archives/C0667PCPVLM/p1727468502511359

https://vagov.ddog-gov.com/logs?query=host%3Avets-api-sidekiq-78cb987f7c-f8h2f%20service%3Avets-api%20container_id%3A6374b9e1b633494bff72e4ff01051e485ed0428ba2930905a5b2f7efa22046a3%20filename%3A0.log%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&context_event=AZI1JI1SAABvCtFY_ewH-QAs&event=AgAAAZI1JII3u3W5OgAAAAAAAAAYAAAAAEFaSTFKSTFTQUFCdkN0RllfZXdILVFBcwAAACQAAAAAMDE5MjM1MjktYjZmMi00NDcxLWIwNGMtZGRhMTM5MmJhYmU1&fromUser=false&messageDisplay=inline&refresh_mode=sliding&screenId=vk2-6zi-zzu&screenName=benefits---form-527-pension-benefits&storage=hot&stream_sort=time%2Cdesc&to_event=AgAAAZI1JILVu3W5RAAAAAAAAAAYAAAAAEFaSTFKSTFTQUFCdkN0RllfZXdILVFBMgAAACQAAAAAMDE5MjM1MjktYjZmMi00NDcxLWIwNGMtZGRhMTM5MmJhYmU1&viz=&from_ts=1727468138071&to_ts=1727468438230&live=false

**Comment by wayne-weibel** [comment]
There is a malformed pdf attachment - using HexaPDF did not resolve the datestamp issue, which is required for the manual remediation
```
irb(main):056> run_pdftk(9913308)
SavedClaim::Pension 9913308 - tmp/pdfs/21P-527EZ_9913308.pdf
 ... tmp/335b5699a6cb1cffd440de97b1177831.pdf
PersistentAttachments::PensionBurial 583874 - clamav_tmp/b252fc45852a9f78d294682077bac465
{"host":"vets-api-sidekiq-58566559cc-vgdf5","application":"vets-api-server","environment":"production","timestamp":"2024-10-02T15:48:11.164169Z","level":"error","level_index":4,"pid":704790,"thread":"12060","file":"/app/lib/pdf_utilities/datestamp_pdf.rb","line":46,"named_tags":{"dd":{"env":"eks-prod","service":"vets-api","version":"e262b9c4e10c01010af572e5e7653f7e950f5d97","trace_id":"0","span_id":"0"},"ddsource":"ruby"},"name":"Rails","message":"Failed to generate datestamp file: pdftk failed with command\n/usr/bin/pdftk clamav_tmp/b252fc45852a9f78d294682077bac465 stamp tmp/ffcd3c850067a44afdc921afa069f91a output tmp/8a4a2d842c88e75a3973dda1372a6555.pdf\ncommand output was:\nError: Unexpected Exception in open_reader()\nJava Exception:\njava.lang.ClassCastException: class com.gitlab.pdftk_java.com.lowagie.text.pdf.PdfDictionary cannot be cast to class com.gitlab.pdftk_java.com.lowagie.text.pdf.PRStream (com.gitlab.pdftk_java.com.lowagie.text.pdf.PdfDictionary and com.gitlab.pdftk_java.com.lowagie.text.pdf.PRStream are in unnamed module of loader 'app')\n\tat com.gitlab.pdftk_java.com.lowagie.text.pdf.PdfReader.readDocObj(PdfReader.java:1144)\n\tat com.gitlab.pdftk_java.com.lowagie.text.pdf.PdfReader.readPdf(PdfReader.java:519)\n\tat com.gitlab.pdftk_java.com.lowagie.text.pdf.PdfReader.<init>(PdfReader.java:172)\n\tat com.gitlab.pdftk_java.com.lowagie.text.pdf.PdfReader.<init>(PdfReader.java:161)\n\tat com.gitlab.pdftk_java.InputPdf.add_reader(InputPdf.java:73)\n\tat com.gitlab.pdftk_java.TK_Session.add_reader(TK_Session.java:61)\n\tat com.gitlab.pdftk_java.TK_Session.open_input_pdf_readers(TK_Session.java:78)\n\tat com.gitlab.pdftk_java.TK_Session$Parser.parse_state_output_filename(TK_Session.java:854)\n\tat com.gitlab.pdftk_java.TK_Session$Parser.parse(TK_Session.java:209)\n\tat com.gitlab.pdftk_java.TK_Session.parse(TK_Session.java:1112)\n\tat com.gitlab.pdftk_java.pdftk.main_noexit(pdftk.java:184)\n\tat com.gitlab.pdftk_java.pdftk.main(pdftk.java:161)"}
lib/pdf_utilities/datestamp_pdf.rb:128:in `stamp_pdf': pdftk failed with command (PdfForms::PdftkError)
/usr/bin/pdftk clamav_tmp/b252fc45852a9f78d294682077bac465 stamp tmp/ffcd3c850067a44afdc921afa069f91a output tmp/8a4a2d842c88e75a3973dda1372a6555.pdf
command output was:
Error: Unexpected Exception in open_reader()
Java Exception:
java.lang.ClassCastException: class com.gitlab.pdftk_java.com.lowagie.text.pdf.PdfDictionary cannot be cast to class com.gitlab.pdftk_java.com.lowagie.text.pdf.PRStream (com.gitlab.pdftk_java.com.lowagie.text.pdf.PdfDictionary and com.gitlab.pdftk_java.com.lowagie.text.pdf.PRStream are in unnamed module of loader 'app')
        at com.gitlab.pdftk_java.com.lowagie.text.pdf.PdfReader.readDocObj(PdfReader.java:1144)
        at com.gitlab.pdftk_java.com.lowagie.text.pdf.PdfReader.readPdf(PdfReader.java:519)
        at com.gitlab.pdftk_java.com.lowagie.text.pdf.PdfReader.<init>(PdfReader.java:172)
        at com.gitlab.pdftk_java.com.lowagie.text.pdf.PdfReader.<init>(PdfReader.java:161)
        at com.gitlab.pdftk_java.InputPdf.add_reader(InputPdf.java:73)
        at com.gitlab.pdftk_java.TK_Session.add_reader(TK_Session.java:61)
        at com.gitlab.pdftk_java.TK_Session.open_input_pdf_readers(TK_Session.java:78)
        at com.gitlab.pdftk_java.TK_Session$Parser.parse_state_output_filename(TK_Session.java:854)
        at com.gitlab.pdftk_java.TK_Session$Parser.parse(TK_Session.java:209)
        at com.gitlab.pdftk_java.TK_Session.parse(TK_Session.java:1112)
        at com.gitlab.pdftk_java.pdftk.main_noexit(pdftk.java:184)
        at com.gitlab.pdftk_java.pdftk.main(pdftk.java:161)

        from lib/pdf_utilities/datestamp_pdf.rb:44:in `run'
        from (irb):20:in `pdftk_stamp'
        from (irb):12:in `block in run_pdftk'
        from (irb):12:in `run_pdftk'
        from (irb):56:in `<main>'
irb(main):057> run_hexapdf(9913308)
SavedClaim::Pension 9913308 - tmp/pdfs/21P-527EZ_9913308.pdf
 ... tmp/f0536bd19d50d30382c15f9d43879f30.pdf
PersistentAttachments::PensionBurial 583874 - clamav_tmp/e1211948ff62141ac810b1c5ee43be41
Problem encountered: undefined method `each_page' for an instance of HexaPDF::Type::Catalog
--> The problem might indicate a faulty PDF or a bug in HexaPDF.
--> Please report this at https://github.com/gettalong/hexapdf/issues - thanks!
root@vets-api-sidekiq-58566559cc-vgdf5:/app# 
```

**Comment by wayne-weibel** [comment]
uploaded to manual remediation folder in sharepoint
