### ISSUE TITLE
Create a Sentry10 Build AMI

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#9578]
## The Problem
We don't yet have a sentry10 "build", that is, an AMI for sentry10 in AWS.

I ran into an error when trying to run the build locally:
```
ansible-playbook -e ref=2c040645cec2adc5339f8fa8a32a2315704562dc -e app=sentry10 -e rebuild=true -i inventory build/create.yml
```
result:
<details>
  <summary>Click to expand!</summary>
  
  ```
TASK [common/docker : Install docker-compose] ************************************************************************************************************************************************************
Thursday 28 May 2020  10:06:08 -0400 (0:00:02.201)       0:06:13.452 ********** 
[DEPRECATION WARNING]: evaluating docker_compose_installation as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the future. Also see 
CONDITIONAL_BARE_VARS configuration toggle.. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
fatal: [ec2-52-222-17-103.us-gov-west-1.compute.amazonaws.com]: FAILED! => changed=true 
  cmd: pip install 'docker-compose==1.25.4'
  delta: '0:00:16.277518'
  end: '2020-05-28 14:06:26.628181'
  msg: non-zero return code
  rc: 1
  start: '2020-05-28 14:06:10.350663'
  stderr: |2-
        DEPRECATION: Uninstalling a distutils installed project (chardet) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Command "/usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-rr34a6/subprocess32/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-pB90zK-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-rr34a6/subprocess32/
    You are using pip version 9.0.3, however version 20.1.1 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
  stderr_lines: <omitted>
  stdout: |-
    Collecting docker-compose==1.25.4
      Downloading https://files.pythonhosted.org/packages/40/91/670b31a1c452cc5f3ed9e1ff905f6c4501a182551dfd8fa1981a8dca2d67/docker_compose-1.25.4-py2.py3-none-any.whl (136kB)
    Collecting backports.ssl-match-hostname<4,>=3.5; python_version < "3.5" (from docker-compose==1.25.4)
      Downloading https://files.pythonhosted.org/packages/ff/2b/8265224812912bc5b7a607c44bf7b027554e1b9775e9ee0de8032e3de4b2/backports.ssl_match_hostname-3.7.0.1.tar.gz
    Collecting backports.shutil-get-terminal-size==1.0.0; python_version < "3.3" (from docker-compose==1.25.4)
      Downloading https://files.pythonhosted.org/packages/7d/cd/1750d6c35fe86d35f8562091737907f234b78fdffab42b29c72b1dd861f4/backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl
    Collecting docker[ssh]<5,>=3.7.0 (from docker-compose==1.25.4)
      Downloading https://files.pythonhosted.org/packages/58/74/379a9d30b1620def158c40b88c43e01c1936a287ebb97afab0699c601c57/docker-4.2.0-py2.py3-none-any.whl (143kB)
    Collecting jsonschema<4,>=2.5.1 (from docker-compose==1.25.4)
      Downloading https://files.pythonhosted.org/packages/c5/8f/51e89ce52a085483359217bc72cdbf6e75ee595d5b1d4b5ade40c7e018b8/jsonschema-3.2.0-py2.py3-none-any.whl (56kB)
    Collecting enum34<2,>=1.0.4; python_version < "3.4" (from docker-compose==1.25.4)
      Downloading https://files.pythonhosted.org/packages/6f/2c/a9386903ece2ea85e9807e0e062174dc26fdce8b05f216d00491be29fad5/enum34-1.1.10-py2-none-any.whl
    Collecting texttable<2,>=0.9.0 (from docker-compose==1.25.4)
      Downloading https://files.pythonhosted.org/packages/ec/b1/8a1c659ce288bf771d5b1c7cae318ada466f73bd0e16df8d86f27a2a3ee7/texttable-1.6.2-py2.py3-none-any.whl
    Collecting requests<3,>=2.20.0 (from docker-compose==1.25.4)
      Downloading https://files.pythonhosted.org/packages/1a/70/1935c770cb3be6e3a8b78ced23d7e0f3b187f5cbfab4749523ed65d7c9b1/requests-2.23.0-py2.py3-none-any.whl (58kB)
    Collecting subprocess32<4,>=3.5.4; python_version < "3.2" (from docker-compose==1.25.4)
      Downloading https://files.pythonhosted.org/packages/32/c8/564be4d12629b912ea431f1a50eb8b3b9d00f1a0b1ceff17f266be190007/subprocess32-3.5.4.tar.gz (97kB)
    Requirement already satisfied: PyYAML<6,>=3.10 in /usr/lib64/python2.7/dist-packages (from docker-compose==1.25.4)
    Collecting cached-property<2,>=1.2.0 (from docker-compose==1.25.4)
      Downloading https://files.pythonhosted.org/packages/3b/86/85c1be2e8db9e13ef9a350aecd6dea292bd612fa288c2f40d035bb750ded/cached_property-1.5.1-py2.py3-none-any.whl
    Requirement already satisfied: six<2,>=1.3.0 in /usr/lib/python2.7/dist-packages (from docker-compose==1.25.4)
    Collecting docopt<1,>=0.6.1 (from docker-compose==1.25.4)
      Downloading https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz
    Collecting ipaddress<2,>=1.0.16; python_version < "3.3" (from docker-compose==1.25.4)
      Downloading https://files.pythonhosted.org/packages/c2/f8/49697181b1651d8347d24c095ce46c7346c37335ddc7d255833e7cde674d/ipaddress-1.0.23-py2.py3-none-any.whl
    Collecting dockerpty<1,>=0.4.1 (from docker-compose==1.25.4)
      Downloading https://files.pythonhosted.org/packages/8d/ee/e9ecce4c32204a6738e0a5d5883d3413794d7498fe8b06f44becc028d3ba/dockerpty-0.4.1.tar.gz
    Collecting websocket-client<1,>=0.32.0 (from docker-compose==1.25.4)
      Downloading https://files.pythonhosted.org/packages/4c/5f/f61b420143ed1c8dc69f9eaec5ff1ac36109d52c80de49d66e0c36c3dfdf/websocket_client-0.57.0-py2.py3-none-any.whl (200kB)
    Collecting paramiko>=2.4.2; extra == "ssh" (from docker[ssh]<5,>=3.7.0->docker-compose==1.25.4)
      Downloading https://files.pythonhosted.org/packages/06/1e/1e08baaaf6c3d3df1459fd85f0e7d2d6aa916f33958f151ee1ecc9800971/paramiko-2.7.1-py2.py3-none-any.whl (206kB)
    Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from jsonschema<4,>=2.5.1->docker-compose==1.25.4)
    Collecting attrs>=17.4.0 (from jsonschema<4,>=2.5.1->docker-compose==1.25.4)
      Downloading https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
    Collecting importlib-metadata; python_version < "3.8" (from jsonschema<4,>=2.5.1->docker-compose==1.25.4)
      Downloading https://files.pythonhosted.org/packages/ad/e4/891bfcaf868ccabc619942f27940c77a8a4b45fd8367098955bb7e152fb1/importlib_metadata-1.6.0-py2.py3-none-any.whl
    Collecting pyrsistent>=0.14.0 (from jsonschema<4,>=2.5.1->docker-compose==1.25.4)
      Downloading https://files.pythonhosted.org/packages/9f/0d/cbca4d0bbc5671822a59f270e4ce3f2195f8a899c97d0d5abb81b191efb5/pyrsistent-0.16.0.tar.gz (108kB)
    Collecting functools32; python_version < "3" (from jsonschema<4,>=2.5.1->docker-compose==1.25.4)
      Downloading https://files.pythonhosted.org/packages/c5/60/6ac26ad05857c601308d8fb9e87fa36d0ebf889423f47c3502ef034365db/functools32-3.2.3-2.tar.gz
    Collecting idna<3,>=2.5 (from requests<3,>=2.20.0->docker-compose==1.25.4)
      Downloading https://files.pythonhosted.org/packages/89/e3/afebe61c546d18fb1709a61bee788254b40e736cff7271c7de5de2dc4128/idna-2.9-py2.py3-none-any.whl (58kB)
    Collecting chardet<4,>=3.0.2 (from requests<3,>=2.20.0->docker-compose==1.25.4)
      Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    Collecting certifi>=2017.4.17 (from requests<3,>=2.20.0->docker-compose==1.25.4)
      Downloading https://files.pythonhosted.org/packages/57/2b/26e37a4b034800c960a00c4e1b3d9ca5d7014e983e6e729e33ea2f36426c/certifi-2020.4.5.1-py2.py3-none-any.whl (157kB)
    Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python2.7/dist-packages (from requests<3,>=2.20.0->docker-compose==1.25.4)
    Collecting bcrypt>=3.1.3 (from paramiko>=2.4.2; extra == "ssh"->docker[ssh]<5,>=3.7.0->docker-compose==1.25.4)
      Downloading https://files.pythonhosted.org/packages/ad/36/9a0227d048e98409f012570f7bef8a8c2373b9c9c5dfbf82963cbae05ede/bcrypt-3.1.7-cp27-cp27mu-manylinux1_x86_64.whl (59kB)
    Collecting cryptography>=2.5 (from paramiko>=2.4.2; extra == "ssh"->docker[ssh]<5,>=3.7.0->docker-compose==1.25.4)
      Downloading https://files.pythonhosted.org/packages/5f/fc/a92bad2460d349ee9eb868f9f9dcddb7c8f42a45677d53a5c663fa251e75/cryptography-2.9.2-cp27-cp27mu-manylinux1_x86_64.whl (2.7MB)
    Collecting pynacl>=1.0.1 (from paramiko>=2.4.2; extra == "ssh"->docker[ssh]<5,>=3.7.0->docker-compose==1.25.4)
      Downloading https://files.pythonhosted.org/packages/de/63/bb36279da38df643c6df3a8a389f29a6ff4a8854468f4c9b9d925b27d57d/PyNaCl-1.4.0-cp27-cp27mu-manylinux1_x86_64.whl (964kB)
    Collecting configparser>=3.5; python_version < "3" (from importlib-metadata; python_version < "3.8"->jsonschema<4,>=2.5.1->docker-compose==1.25.4)
      Downloading https://files.pythonhosted.org/packages/7a/2a/95ed0501cf5d8709490b1d3a3f9b5cf340da6c433f896bbe9ce08dbe6785/configparser-4.0.2-py2.py3-none-any.whl
    Collecting contextlib2; python_version < "3" (from importlib-metadata; python_version < "3.8"->jsonschema<4,>=2.5.1->docker-compose==1.25.4)
      Downloading https://files.pythonhosted.org/packages/85/60/370352f7ef6aa96c52fb001831622f50f923c1d575427d021b8ab3311236/contextlib2-0.6.0.post1-py2.py3-none-any.whl
    Collecting pathlib2; python_version < "3" (from importlib-metadata; python_version < "3.8"->jsonschema<4,>=2.5.1->docker-compose==1.25.4)
      Downloading https://files.pythonhosted.org/packages/e9/45/9c82d3666af4ef9f221cbb954e1d77ddbb513faf552aea6df5f37f1a4859/pathlib2-2.3.5-py2.py3-none-any.whl
    Collecting zipp>=0.5 (from importlib-metadata; python_version < "3.8"->jsonschema<4,>=2.5.1->docker-compose==1.25.4)
      Downloading https://files.pythonhosted.org/packages/96/0a/67556e9b7782df7118c1f49bdc494da5e5e429c93aa77965f33e81287c8c/zipp-1.2.0-py2.py3-none-any.whl
    Collecting cffi>=1.1 (from bcrypt>=3.1.3->paramiko>=2.4.2; extra == "ssh"->docker[ssh]<5,>=3.7.0->docker-compose==1.25.4)
      Downloading https://files.pythonhosted.org/packages/08/29/8001b940ef40e7a25ffe8f3188bc9b118934b513d64f769dbf461e46f4ed/cffi-1.14.0-cp27-cp27mu-manylinux1_x86_64.whl (387kB)
    Collecting scandir; python_version < "3.5" (from pathlib2; python_version < "3"->importlib-metadata; python_version < "3.8"->jsonschema<4,>=2.5.1->docker-compose==1.25.4)
      Downloading https://files.pythonhosted.org/packages/df/f5/9c052db7bd54d0cbf1bc0bb6554362bba1012d03e5888950a4f5c5dadc4e/scandir-1.10.0.tar.gz
    Collecting pycparser (from cffi>=1.1->bcrypt>=3.1.3->paramiko>=2.4.2; extra == "ssh"->docker[ssh]<5,>=3.7.0->docker-compose==1.25.4)
      Downloading https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl (112kB)
    Installing collected packages: backports.ssl-match-hostname, backports.shutil-get-terminal-size, ipaddress, idna, chardet, certifi, requests, websocket-client, pycparser, cffi, bcrypt, enum34, cryptography, pynacl, paramiko, docker, attrs, configparser, contextlib2, scandir, pathlib2, zipp, importlib-metadata, pyrsistent, functools32, jsonschema, texttable, subprocess32, cached-property, docopt, dockerpty, docker-compose
      Found existing installation: backports.ssl-match-hostname 3.4.0.2
        Uninstalling backports.ssl-match-hostname-3.4.0.2:
          Successfully uninstalled backports.ssl-match-hostname-3.4.0.2
      Running setup.py install for backports.ssl-match-hostname: started
        Running setup.py install for backports.ssl-match-hostname: finished with status 'done'
      Found existing installation: chardet 2.0.1
        Uninstalling chardet-2.0.1:
          Successfully uninstalled chardet-2.0.1
      Found existing installation: requests 1.2.3
        Uninstalling requests-1.2.3:
          Successfully uninstalled requests-1.2.3
      Found existing installation: paramiko 1.15.1
        Uninstalling paramiko-1.15.1:
          Successfully uninstalled paramiko-1.15.1
      Running setup.py install for scandir: started
        Running setup.py install for scandir: finished with status 'done'
      Running setup.py install for pyrsistent: started
        Running setup.py install for pyrsistent: finished with status 'done'
      Running setup.py install for functools32: started
        Running setup.py install for functools32: finished with status 'done'
      Running setup.py install for subprocess32: started
        Running setup.py install for subprocess32: finished with status 'error'
        Complete output from command /usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-rr34a6/subprocess32/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-pB90zK-record/install-record.txt --single-version-externally-managed --compile:
        running install
        running build
        running build_py
        creating build
        creating build/lib.linux-x86_64-2.7
        copying subprocess32.py -> build/lib.linux-x86_64-2.7
        running build_ext
        running build_configure
        checking for gcc... no
        checking for cc... no
        checking for cl.exe... no
        configure: error: in `/tmp/pip-build-rr34a6/subprocess32':
        configure: error: no acceptable C compiler found in $PATH
        See `config.log' for more details
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-build-rr34a6/subprocess32/setup.py", line 120, in <module>
            main()
          File "/tmp/pip-build-rr34a6/subprocess32/setup.py", line 114, in main
            'Programming Language :: Python :: Implementation :: CPython',
          File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
            dist.run_commands()
          File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
            self.run_command(cmd)
          File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
            cmd_obj.run()
          File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
            return orig.install.run(self)
          File "/usr/lib64/python2.7/distutils/command/install.py", line 604, in run
            self.run_command('build')
          File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
            self.distribution.run_command(command)
          File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
            cmd_obj.run()
          File "/usr/lib64/python2.7/distutils/command/build.py", line 127, in run
            self.run_command(cmd_name)
          File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
            self.distribution.run_command(command)
          File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
            cmd_obj.run()
          File "/tmp/pip-build-rr34a6/subprocess32/setup.py", line 41, in run
            self.run_command(command)
          File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
            self.distribution.run_command(command)
          File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
            cmd_obj.run()
          File "/tmp/pip-build-rr34a6/subprocess32/setup.py", line 26, in run
            raise RuntimeError(configure_command + ' failed.')
        RuntimeError: sh ./configure failed.
  
        ----------------------------------------
  stdout_lines: <omitted>
  ```
</details>

## Extra Context
- The sentry10 build was very recently merged into master - [link](https://github.com/department-of-veterans-affairs/devops/pull/6929)
- The sentry10 does not yet have a Jenkins job to build it - [link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9539)

## Work to be Done
One of:
- [ ] Run the build ansible-playbook locally to build a sentry10 AMI
or
- [ ] Create a jenkins job first, and use that to run the build and create AMI

**Comment by omgitsbillryan** [comment]
I think my local ansible-playbook error may be related to this: https://github.com/department-of-veterans-affairs/devops/blob/master/Jenkinsfile#L22

**Comment by alexpappasoddball** [comment]
@omgitsbillryan to review

**Comment by omgitsbillryan** [comment]
This is done - here are the PR's that accomplished this:
- https://github.com/department-of-veterans-affairs/devops/pull/6929
- https://github.com/department-of-veterans-affairs/devops/pull/7133
- https://github.com/department-of-veterans-affairs/devops/pull/7173
